### PR TITLE
replace deprecated druid.port by druid.plaintextPort in docs

### PR DESCRIPTION
**Pull request by QiuMM**

### CODE REVIEW

**Comment by QiuMM** [comment]
CI build error:
```
[ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1,350.981 s <<< FAILURE! - in TestSuite
[ERROR] testRealtimeIndexTask(org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest)  Time elapsed: 10.395 s  <<< FAILURE!
java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.postEvents(ITRealtimeIndexTaskTest.java:122)
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.testRealtimeIndexTask(ITRealtimeIndexTaskTest.java:56)
Caused by: java.util.concurrent.ExecutionException: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.postEvents(ITRealtimeIndexTaskTest.java:122)
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.testRealtimeIndexTask(ITRealtimeIndexTaskTest.java:56)
Caused by: org.jboss.netty.channel.ChannelException: Faulty channel in resource pool
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.postEvents(ITRealtimeIndexTaskTest.java:122)
	at org.apache.druid.tests.indexer.ITRealtimeIndexTaskTest.testRealtimeIndexTask(ITRealtimeIndexTaskTest.java:56)
Caused by: org.jboss.netty.channel.ChannelException: Failed to handshake with host[https://127.0.0.1:8101]
Caused by: java.nio.channels.ClosedChannelException
```

Is this a bug?

**Comment by fjy** [comment]
@QiuMM we have a bunch of non-deterministic tests that don't fail locally but fail once Travis-CI runs

**Comment by QiuMM** [comment]
Got it, thanks.

**Comment by b-slim** [comment]
@QiuMM is there any docs fixup as well?

**Comment by QiuMM** [comment]
@b-slim all related docs have been fixed.

**Pull request merged**
