### PR TITLE
[Benchmarking] Call blackhole#consume() on collections instead of iterating through each element

### PR DESCRIPTION
**Pull request by justinborromeo**
Currently, in the query benchmarks, the collection of results is being iterated through and `blackhole.consume()` is being called on each result individually.  According to [this comment](https://stackoverflow.com/questions/54488216/does-the-effect-of-jmh-blackholeconsume-vary-depending-on-the-type-of-object?noredirect=1#comment95783891_54488216) on SO, it would be better to call `consume` once on the collection.  Although the effect of this change is likely trivial, it's probably a better practice to remove unnecessary overhead on our benchmarks.

If anyone disagrees with the opinion in the SO comment, lmk.

### CODE REVIEW

**Comment by drcrallen** [comment]
it is entirely possible that there are lazy transforms that can affect the results here. I can't think of any off the top of my head in these specific code paths but guava's transforming list wrappers are used pretty extensively in druid.

**Comment by justinborromeo** [comment]
Fair enough.  If it's too risky given that we're not certain about the change's effects, I can close the PR.

**Comment by drcrallen** [comment]
The different usage mechanisms make this harder to track, but looking at `org.apache.druid.java.util.common.guava.Sequence#toList` (which is the underlying call in a bunch of places here) the only implementations are the eager accumulation into an array list. So this PR is probably safe as is.

To protect against future development, can you please add a java doc to `org.apache.druid.java.util.common.guava.Sequence#toList` indicating that various benchmarks rely on this method to eagerly accumulate?

**Comment by justinborromeo** [comment]
GroupByBenchmark results for `master` and this branch:

image

Based on the above stats, it would appear as if there was a slight decrease (~2.3%) in score for the 10 tests randomly selected from the GroupBy benchmark.  Tests 1 and 10, with their -7.3% and -5.8% change, seem like outliers.  @gianm is this enough to determine whether dead-code elimination is happening?

Benchmark info:
- Run on: MacBook Pro
- Heap Memory: 8 GB
- GC: G1
- Warmup Iterations: 15
- Benchmark Iterations: 30

**Comment by drcrallen** [comment]
I'm good with these numbers, on a macbook pro it is really hard to gauge actual benchmark changes https://metamarkets.com/2015/effect-of-frequency-governor-on-java-benchmarking/

**Pull request merged**
