### PR TITLE
Remove unnecessary path param from auto compaction api

### PR DESCRIPTION
**Pull request by jihoonson**
For adding a new auto compact configuration, the path param `dataSource` isn't necessary because it's also in the compaction configuration.

### CODE REVIEW

**Comment by jihoonson** [comment]
@QiuMM thanks for the quick review. 

BTW, would you mind checking your gmail? I sent an email several days ago. Please check it.

**Comment by QiuMM** [comment]
@jihoonson sorry, I have not logined that gmail for a long time. I'll check it now.

**Comment by jihoonson** [comment]
I also changed the api to set max compaction task slots from `/druid/coordinator/v1/config/compaction` to `/druid/coordinator/v1/config/compaction/taskslots`.

**Comment by jihoonson** [comment]
@QiuMM thanks for checking!

**Pull request merged**
