### PR TITLE
define new high-level abstract storage interfaces with a default mmap implementation

### PR DESCRIPTION
**Pull request by weijietong**
This PR is to solve the feature issue #3715  , I defined the high level abstract index storage interfaces , also with  a default mmap implementation , and a related test case. for a simple explain:

The Directory class is a flat list of files which may be xx.smooth 、xx.meta 、xx.drd and some other Druid temp files or durable files.
The IndexInput class is an abstract interface to read the content of some index files.
The IndexOutput class is an abstract interface to write index data to some files of the Directory.
From Druid indexing aspect, the indexing files are written once and read more, the interface definition also observe the contract. 

If this PR was accepted, I will rewrite other related codes to replace the java nio ByteBuffer to IndexInput at the interface level.

### CODE REVIEW

**Comment by leventov** [comment]
Did you write this code entirely yourself, or (partially) copied from some other project?

This kind of byte management frameworks for Java always spawn writing a lot of boilerplate code for copying/comparing/streaming/converting bytes around, in which it's very easy to make a bugs. So if introducing this abstraction, I think it should be borrowed from other project in heavy use, like Hadoop, Spark, Cassandra, Netty, because it likely has little bugs, and the set of abstractions itself is proven to work. This framework should preferably be copied into the Druid codebase, not added as a dependency.

**Comment by weijietong** [comment]
to be honestly, partially copied from Lucene project as I ever mentioned in the google group ,and removed and rewrite  some code according to Druid. for now I rewrite the default mmap implementation , and the IndexInput interface seems to replace the ByteBuffer perfectly with the read /write/slice/seek/getFilePoint methods as I tested at my own codebase. hope that we can continue this job to work around this problem. tks for your reply.

**Comment by weijietong** [comment]
*  refactor the GenericIndexed and the corresponding test case with the IndexInput interface 
*  The refactoring follows the rule that a old method with the ByteBuffer param will have a corresponding method named ending with ’V1‘ suffix . 
* The InputSplit interface adds a duplicate method.
by the way ,do I need to submit this as another PR ?and what about subsequent submitting ? any other  refactoring guide will be appreciate.

**Comment by weijietong** [comment]
@cheddar I want to move the codes under package `io.druid.java.util.common.io.smoosh` into druid-processing bundle ,as refactoring the Smooth will produce a dependence on the Directory class of druid-processing bundle. wait for your idea.

**Comment by leventov** [comment]
Some observations:
- License should be different, not ASF. Look at existing files.
- It's good that interfaces are based on Lucene code. Could you please demonstrate the diff with actual Lucene source? E. g. by cloning Lucene repo, and making a PR (within your cloned repo, from one branch to another), so that Github highlights diffs. Or any other way.
 - Words like `Index`, `Input`, `Output` are already massively overused in Druid, please try to choose more distinctive names for interfaces.
 - Lack of clear documentation on interfaces, describing their purpose.
 - Please demonstrate there are no performance regressions, because of adding another layer of indirection, in the Druid subsystems which use those interfaces.

**Comment by weijietong** [comment]
@leventov tks for your advise ,I have done a V9 version implementation. codes、document and benchmark will be update soon .

**Comment by weijietong** [comment]
# New interfaces  describe
* Directory  is a container of files . We create files here,open IndexInput for a file to read data we have written,open a IndexOutput for a file to write data into.
* IndexInput  (sorry for @leventov   I have not got a good name ,maybe FileInput or something good ? ，for now to interpret my solution first,just have this name ,if find a good name ,I will refactor the code later) behaves like the ByteBuffer. We use seek() to move file point, use length() to get the capacity ,use slice() to get a scliced one what needs to be noticed is that the sliced one's  file point will keep on growing compared to its original one,use duplicate() to have a fresh duplicated one
* IndexOutput  a way to write data into a file of the Directory
* RandomAccessInput:  As ` Indexed<T> `needs to random access a file ,this class supply a way to absolue read data from a file. The related methods need to be thread safe. subclasses may override this IndexInput.randomAccess() method for performance reason like what ByteBufferIndexInput class does.
* bytecode format rule : the interface level to restrict data type like int/long/short to use big-endian byte code order. As Druid LongsLong encoding does not restrict byte code order, The LongsLongEncodingWriter and LongsLongEncodingReader class's write long method was specific written using bytes for compatibility . BTW,as Druid's other type byte code order are all big-endian ,why not having a uniform byte code order.
* conventional column smooth file size is Integer.MAX_VALUE. So the interface to convert long to int is considering correctly. I have also noticed the PR #3743 that seems split larger columns into separate smooth files which also observes the Integer.MAX_VALUE rule.
# What have done
* implement a mmap version Directory
* v9 version implemention based on Directory, using a new  DirectoryBasedTmpIOPeon not the TmpFilePeon to wite temp files like .header,.format,.drd and so on while creating directory,bitmap,metrics,timestamp index data. A finally segement Directory will only have .smooth ,meta.smooth,version.bin files.
* remove smooth related files from  java-util bundle ,as these codes  are closely bound up with the processing bundle. 

# What have to do later
* IndexIO has a static  `checkFileSize(File indexFile) ` which needs to have a similar Directory version by considering backward compatibility.
* V9 version's RTree have not refactored.
* legacy version refactor.
*  `ComplexMetricSerde. deserializeColumn(IndexInput indexInput, ColumnBuilder builder) `  needs to be implemented in other bundles besides the processing bundle.
* The old interface has to be refactored using the Directory interface in the IndexIO , IndexMerger  maybe sometime later. This work will affects the calling methods in other bundles.


# Benchmark 
* add a benchmark class:io.druid.benchmark.indexing.IndexMergeDirectoryBenchmark
* here are the benchmark under the linux os with 24 cores :

>
Benchmark                                      (numSegments)  (rollup)  (rowsPerSegment)  (schema)  Mode  Cnt        Score        Error  Units
IndexMergeDirectoryBenchmark.mergeV9                       5      true             75000     basic  avgt   25  9240124.749 ± 347646.305  us/op
IndexMergeDirectoryBenchmark.mergeV9                       5     false             75000     basic  avgt   25  9108096.768 ± 353987.000  us/op
IndexMergeDirectoryBenchmark.mergeV9Directory              5      true             75000     basic  avgt   25  9123815.002 ± 408413.806  us/op
IndexMergeDirectoryBenchmark.mergeV9Directory              5     false             75000     basic  avgt   25  9111214.891 ± 353926.469  us/op

**Comment by weijietong** [comment]
@leventov @gianm @cheddar @fjy please review the codes. glad to announce that through implementing the abstract interface for our specific env (concrete: Aliyun MaxCompute),I have got my Druid offline job running.

**Comment by cheddar** [comment]
@weijietong Thanks for the contribution.  We've spent some time looking at it and have wanted something similar to happen in order to enable us to switch from using `ByteBuffer` to using something based on `Unsafe` which should be significantly faster (generally things tend to run in 2/3 the time).

In looking at the interfaces, there are a few things that we expect to have real performance implications (one example is the proposal to move everything to big endian, that will actually end up slowing down speeds by about 3x or 4x).  In general, it is important to use native endianness when working with memory mapped files.

We are putting together a counter proposal that would actually return the datasketches `Memory` interface instead of the `DataInput` and `DataOutput` interfaces that you borrowed from Lucene.  The hope is that the `Memory` interface will be a bit more in-line with the needs of data processing, hopefully it is also something you can implement on top of your distributed filesystem implementation.

**Comment by weijietong** [comment]
@cheddar Thanks for your reply. First ,I want to explain about byte code order. From what I learned from the current Druid codes, most of the byte code order is big endian ,except the longlong encoding type which uses the native endianness . While implementing this PR ,I also observe this rule, so ,for the mmap default implementation, there is no performance slowing down as you predicated .
For the `Memory` proposal ,could you give a link ? what about the plan ? I hope that the new proposal should also contain an high abstract interface. Something like `mmap` 、`Unsafe` should be a specific technology implementation, which should be a choice for users to choose or implement by themselves.

**Comment by cheddar** [comment]
@weijietong Yeah, you are right, a lot of the stuff is using big-endian values.  That wasn't intentional though, it was a historical accident (I didn't realize it until I spent a bit of time trying to read segments with `Unsafe`...).  Given the known performance differences between native endianess and non-native, I'd prefer not to enshrine that mistake and instead work to fix it in future versions.

Fwiw, the `Memory` interface I'm talking about is at https://github.com/DataSketches/sketches-core/blob/master/memory/src/main/java/com/yahoo/memory/Memory.java

It has an implementation that uses `Unsafe`, but should also be individually implementable to not use `Unsafe`.

**Comment by fjy** [comment]
@weijietong apologies for the delay. I am just now looking at this thread and proposal

**Comment by leventov** [comment]
I support @cheddar, we big endianness is bad, let's use native endianness.

If we decide to use `Memory` or similar `ByteBuffer` replacement (I like this idea as well), I think it should come as a separate PR and only after that this PR (modified to use Memory) should be applied.

**Comment by weijietong** [comment]
I think the key point here is to have a good design interface , not byte code endianness implementation detail . As @cheddar  has mentioned, big endianness is a history accident. btw, the origin history reason of big endianness is some usage like `com.google.common.primitives.Ints.toByteArray` . Also `DataInput.readLong()  ,readInt() ....` can be override or refactored to have ByteOrder param.

From my opinion , `Memory` does not seem different from `IndexInput` or `IndexOutput`. And `Unsafe` is just a different implementation detail  relative to `ByteBuffer or mmap`. By the way `Memory` does not have `position, limit, mark, flip ,rewind` concepts, it would be a huge and hard work to refactor Druid codes ,as the concepts above was massively used.

**Comment by leerho** [comment]
@weijietong I can see that you have put a great deal of effort into this proposal and your work is greatly appreciated!

Unfortunately, the devil is in the details.

The position, limit, mark, flip, rewind (PLMFR) concepts in ByteBuffer are there to enable efficient alternating write / read sequences for IO streams of bytes, for example using TCP/IP sockets. TCP/IP specifies Big-Endian for the transmission elements, like source/destination address, port, etc, but the endianness for the payload is up to the higher layers.

The fact that ByteBuffer uses Big-Endian as the default is historical and likely tied to its early use with socket streams or because Sun used SPARC CPUs. Note that the default for an allocated or wrapped LongBuffer is Native-Order and cannot be changed, while a LongBuffer view inherits its endianness from the parent ByteBuffer.

Today, Little-Endian is the default for virtually all large systems (Intel and AMD CPUs). The fact that folks did not bother to specify Native-Endian for reading and writing into memory and memory-mapped files is indeed unfortunate as it is very inefficient.

The PLMFR concepts in ByteBuffer get in the way if you want to efficiently and arbitrarily read and write arrays and fields into packed data structures in memory or memory-mapped files. 

Consider a toy packed structure similar to: 

    typedef struct {       //offsets
        int intArr[8]      //0
        long longArr[8];   //32
        double dblsArr[8]; //96
    } byteArr

And the task is to write these 3 arrays in reverse order:

With ByteBuffer:

    ByteBuffer bb = ByteBuffer.wrap(byteArr);
    bb.order(ByteOrder.LITTLE_ENDIAN);
    
    bb.position(96);
    DoubleBuffer db = bb.asDoubleBuffer();
    db.put(dblsArr, 0, 8);
    
    bb.position(32);
    LongBuffer lb = bb.asLongBuffer();
    lb.put(longArr, 0, 8);
    
    bb.position(0);
    IntBuffer ib = bb.asIntBuffer();
    ib.put(intArr, 0, 8);

With Memory:

    Memory mem = new NativeMemory(byteArr);
    mem.putDoubleArray(96, dblsArr, 0, 8);
    mem.putLongArray(32, longArr, 0, 8);
    mem.putIntArray(0, intArr, 0, 8);

The ByteBuffer approach requires the creation of 3 additional objects and 3 changes to position!
Each of the Memory calls are directly tied to a single Unsafe call, which is converted to CPU intrinsics by the JIT compiler.

The Memory package also allows wrapping a ByteBuffer for backward compatibility:

    Memory mem = new NativeMemory(byteBuffer);

This allows simultaneous views of a region in memory from the ByteBuffer or from Memory.
For those cases where the PLMFR concepts are really required or the historical data was inadvertently written Big-Endian, the user can choose the ByteBuffer view.  New applications could use Memory directly, thus provide for a gradual transition away from the Big-Endian assumptions as well as away from the ByteBuffer entirely.

Memory enables creating memory regions and mapped files larger than 2 GB, and for the really critical performance cases, Memory allows direct access to the Unsafe class, all caveats hereby included :)

Unsafe (and thus Memory) are intentionally only Native-Endian for performance reasons. 

***
I do not consider the proposed DataInput / DataOutput and IndexInput / IndexOutput to be similar to Memory at all. Instead, the DataInput / DataOutput classes could wrap or include Memory objects and have access to a very rich (and fast) API for reading & writing all the primitive types and their corresponding arrays, access to large (> 2GB) off-heap memory and memory-mapped files, and dual views into ByteBuffers if required. 

As @cheddar pointed out, the current assumption of Big-Endian would continue the performance pain going forward. Unfortunately, specifying a Byte-Order parameter for every primitive read/write call would be a performance killer.

I would like to propose that we work together to find a solution for Druid going forward. I would be glad to help you understand the Memory package and how to efficiently use it, and if some extensions to the Memory package is really required, it is open for discussion!

**Comment by weijietong** [comment]
@leerho thanks for your idea. I am not insisting on my propose. I want to point out that as you gave examples : 
```
Memory mem = new NativeMemory(byteArr);
mem.putDoubleArray(96, dblsArr, 0, 8);
mem.putLongArray(32, longArr, 0, 8);
mem.putIntArray(0, intArr, 0, 8);
```
it's hard to give out the values like `0 , 32 , 96` relative to current Druid codes, and I agree NativeMemory may save some cpu instructions through using `Unsafe` ,but I think `NativeMemory` is a specific storage implementation eg memory. so what about other storage implementations like hdfs ,which only operates byte stream oriented ,then `Unsafe` can not give any help.

So I want to point out that we are now defining a interface A ,then we implement that interface A ,and utilize some performance better techs like `mmap` ,`Unsafe` ,`native ByteBuffer`.

I would also be pleasure to see that we find out a better solution to let Druid run on different storage platforms without too pain refactor works . It's open for discussion too , everybody!

**Comment by leerho** [comment]
@weijietong, underneath the covers ByteBuffer uses Unsafe, as do many other performance critical core java classes.  Applying it to hdfs streams should not be a problem :)

**Comment by leventov** [comment]
@weijietong regarding absence of position and limit in `Memory` (other fields are almost never used), If you try to always use them and so keep the source code simpler, what Druid currently does, it results into a lot of ByteBuffer object allocations via `slice()`, `asReadOnlyBuffer()`, etc. I see *millions* of `DirectByteBufferR` objects in heaps of our production Druid historical nodes.

@cheddar @leerho do you have any specific plans to start migration from `ByteBuffer` to `Memory`?

**Comment by weijietong** [comment]
@leventov I also want to know the plan of ```Memory``` ,If ```Memory``` is able to highly abstract the file system ,I will doubt whether the apache project ```Arrow``` is better , which is column oriented ,of course ,with off heap memory allocation.

**Pull request closed without merging**
