### PR TITLE
Lookback query

### PR DESCRIPTION
**Pull request by michael-trelinski**
Please review these changes.  The lookback query is an exciting new feature that we've been using for a while at my company.

It supports a cohort from a query or dataSource useful for trend analysis between Periods.

Example:

Data:
[ (T-1, 1), (T-2, 2), (T-3, 3) ]

Possible cohort:
T-1 join T-2 = 1,2
T-2 join T-3 = 2,3
T-3 join _ = 3,null

Example query and results are in the attached documentation.

### CODE REVIEW

**Comment by michael-trelinski** [comment]
@a2l007 Please add refactor the movingAverage/rollingAverage when that is accepted separately.

Will Sketches supported?

**Comment by jihoonson** [comment]
@michael-trelinski thank you for your contribution! Would you please write a proposal for this PR? Here is the link: https://github.com/apache/incubator-druid/issues/new/choose.

**Comment by michael-trelinski** [comment]
> @michael-trelinski thank you for your contribution! Would you please write a proposal for this PR? Here is the link: https://github.com/apache/incubator-druid/issues/new/choose.

Should I add this as a Feature/Change or a Proposal?  I can see merits for both.

Also, IntelliJ lied to me and the unit tests were broken, so I pushed another commit, which hopefully fixes it.

**Comment by jihoonson** [comment]
I think `Feature/Change` label is for asking some new features or changes of existing features to the community. So, it is more about what is needed and why. `Proposal` is `Feature/Change` + how to implement and rationale about its design.

I think `Proposal` is more proper for your case.

**Pull request closed without merging**
