### PR TITLE
Web console: Adding a server view that can display all servers

### PR DESCRIPTION
**Pull request by vogievetsky**
This PR is the web console followup to https://github.com/apache/incubator-druid/pull/7654 which satisfies https://github.com/apache/incubator-druid/issues/7005

The "Data servers" view is renamed to "Servers":

Like so:

after

This is how it used to look:

before

This change is pretty cool because it increases the utility of that view while also reducing complexity.
Notice that you can now group the table by "Type".

Misc important notes:

- To save space there is now a `Detail` field for the table that is the load queue status for historical servers and last task (+ blacklist date) run for MMs
- `Usage` is similarly overloaded to be capacity usage or task slot usage... I think it makes sense
- A few properties of the react table moved to the default declaration
- Fixed a typos and little issues discovered during coding
- Extracts a few magic numbers from SCSS into constants and fixes some spacing issues
- This PR fixes https://github.com/apache/incubator-druid/issues/7753
- This PR makes the Query view resizable (fixes https://github.com/apache/incubator-druid/issues/7559)
- This PR offers more SQL context options (fixes https://github.com/apache/incubator-druid/issues/7560)

### CODE REVIEW

**Comment by fjy** [comment]
Can we have data/query/master servers and then change 'Type' to be 'Process type'?

**Comment by clintropolis** [comment]
travis failure looks legitimate https://travis-ci.org/apache/incubator-druid/jobs/537985537#L1726

```
[INFO] FAIL src/components/sql-control/sql-control.spec.tsx
[INFO]   ● Test suite failed to run
[INFO] 
[INFO]     TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):
[INFO]     src/components/sql-control/sql-control.spec.tsx:30:9 - error TS2322: Type '(query: string, bypassCache: boolean, wrapQuery: boolean) => void' is not assignable to type '(query: string, context: Record<string, any>, wrapQuery: boolean) => void'.
[INFO]       Types of parameters 'bypassCache' and 'context' are incompatible.
[INFO]         Type 'Record<string, any>' is not assignable to type 'boolean'.
[INFO] 
[INFO]     30         onRun={(query: string, bypassCache: boolean, wrapQuery: boolean) => {}}
[INFO]                ~~~~~
[INFO] 
[INFO]       src/components/sql-control/sql-control.tsx:61:3
[INFO]         61   onRun: (query: string, context: Record<string, any>, wrapQuery: boolean) => void;
[INFO]              ~~~~~
[INFO]         The expected type comes from property 'onRun' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<SqlControl> & Readonly<SqlControlProps> & Readonly<{ children?: ReactNode; }>'
```

**Comment by vogievetsky** [comment]
I am not sure what is the best way to detect the data/query/master configuration of the servers. It is just a deployment thing for now right? I suggest we merge this PR as is and then iterate on top of this view. From just a bit of time spent playing with it is is way more functional than what used to be there previously.

**Comment by gianm** [comment]
> I am not sure what is the best way to detect the data/query/master configuration of the servers. It is just a deployment thing for now right? I suggest we merge this PR as is and then iterate on top of this view. From just a bit of time spent playing with it is is way more functional than what used to be there previously.

Yeah, it's just a deployment thing. It won't show up in any way that the console can access. I agree that it's best to merge the PR now and worry about server types in the future.

**Pull request merged**
