### PR TITLE
Minor Spelling Error

### PR DESCRIPTION
**Pull request by nieroda**
[ Minor Spelling Error ]

Came across while reading the docs.

### CODE REVIEW

**Comment by jon-wei** [comment]
I believe that's intentional, it's setting the password for the `druid@localhost` user

**Comment by nieroda** [comment]
@jon-wei  I thought that at first, however the following setup lines show user and pass as druid

```druid.metadata.storage.connector.user=druid
druid.metadata.storage.connector.password=druid
```

**Comment by jon-wei** [comment]
Ah I see, good catch!

**Comment by jon-wei** [comment]
Could you please change the `druid.metadata.storage.connector.password=druid` line instead?

The sqlserver/postgresql docs use `diurd` consistently as the example password, and `intellij-setup.md` is written to expect `diurd` as the mysql example password as well

**Comment by nieroda** [comment]
Sure 👍

**Comment by jon-wei** [comment]
Thanks! (skipping CI for doc-only change)

**Pull request merged**
