### PR TITLE
Web console: added bulk supervisor actions

### LINKED ISSUE #7861: New Druid console is frozen until the supervisor is completely suspended/terminated
### Affected Version

0.14.x, 0.15.x

### Description

Screen Shot 2019-06-10 at 5 53 24 PM

As seen in the above screenshot, the Druid console becomes frozen until the supervisor is completely suspended/terminated. Since suspending/terminating a supervisor might take some time, it would be better if users can do something else while waiting for the supervisor to be suspended/terminated.

### PR DESCRIPTION
**Pull request by vogievetsky**
Added a more menu to the web console supervisor view to be able to call the bulk supervisor suspend/resume/terminate APIs

image

Also makes the async action dialog work better for long running tasks, fixes #7861

### CODE REVIEW

**Comment by gianm** [comment]
This operation can take a while, would some sort of progress indicator be shown to the user?

**Comment by vogievetsky** [comment]
@gianm in that case this happens: https://github.com/apache/incubator-druid/issues/7861 there should probably be a way to run that operation in the background...

**Comment by vogievetsky** [comment]
BTW: you can see me develop this feature here: https://www.youtube.com/watch?v=u5Bl1jJzVIU

**Comment by vogievetsky** [comment]
Made it work with long running actions. This now fixes #7861.

**Pull request merged**
