### PR TITLE
Rename io.druid to org.apache.druid.

### PR DESCRIPTION
**Pull request by gianm**
What I did for this:

1. Move all directories containing `io/druid` into directories containing `org/apache/druid`.
2. Replace all strings `druid-io/druid` with `apache/incubator-druid` (intended to update the Github repo links).
3. Replace all strings `io.druid` with `org.apache.druid`.
4. Replace all strings `io/druid` with `org/apache/druid`.
5. Change some back: io.druid still must be the groupId for the parent pom, and io.druid is still the groupId for druid-console (we should reconcile these both later).
6. Move all META-INF io.druid.initialization.DruidModule files to org.apache.druid.initialization.DruidModule.
7. Remove some apparently unintentionally committed files: processing/benchmarks/io.druid.collections.bitmap.RangeBitmapBenchmarkTest.html, processing/benchmarks/io.druid.collections.bitmap.RangeBitmapBenchmarkTest.jsonp, processing/benchmarks/io.druid.collections.bitmap.UniformBitmapBenchmarkTest.html, and processing/benchmarks/io.druid.collections.bitmap.UniformBitmapBenchmarkTest.jsonp, from #5275.
8. Update the monitors migration code from the MonitorsConfig class to automatically migrate `com.metamx.metrics` and `io.druid.java.util.metrics` to `org.apache.druid.java.util.metrics`.
9. Reorder some dimensions in inner queries in CalciteQueryTest for some reason (?). The planner possibly travels down different internal paths based on package names in, perhaps, toString operators? I'm not sure.
10. Updated `prototest.desc` in the protobuf test package by running `protoc ProtoTest.proto -o prototest.desc`.

### CODE REVIEW

**Comment by drcrallen** [comment]
@gianm any chance there's a way to get `git` to recognize these as renames instead of drops and adds?

As it stands, I don't think a merge from master would be tolerable for any outstanding PR as they would all just be klobbered

**Comment by b-slim** [comment]
👍 after test, my browser crashes when loading pages...will have to trust @gianm on this one.

**Comment by gianm** [comment]
@drcrallen Git actually can figure out that these are renames, but you must change these configs first:

```
git config --local diff.renameLimit 5000
git config --local merge.renameLimit 5000
```

By default, git will disable rename detection if the number of files is >400 for diffs or >1000 for merges.

**Comment by himanshug** [comment]
added labels for `ReleaseNotes` and `Compatibility` as this one will definitely break all extensions.

+1 after the successful build.

**Comment by gianm** [comment]
FYI, I put the steps I used here in the top comment. Parts (6) and (7) were just done now, I missed them in the first commit, and they resulted in some of the test failures.

**Comment by gianm** [comment]
Ah, @himanshug your comment makes me realize we should also update the migration code in MonitorsConfig. I'll do that now.

**Comment by gianm** [comment]
Added a fix for protobuf tests and re-pushed. The unit tests all pass on my machine, although I haven't tried the integration tests there. Will keep monitoring them in Travis.

**Comment by gianm** [comment]
ok here we go!

**Comment by drcrallen** [comment]
@gianm get's a major line count boost with this one :)

**Comment by gianm** [comment]
really good at writing import statements

**Pull request merged**
