### PR TITLE
Protobuf parser: nested messages and fileds, define any message name to parse

### PR DESCRIPTION
**Pull request by rpashuto**
Problems:
**1.** _ProtoBufInputRowParser_ always parses only the first protobuf message.
Now, it has the same behaviour by default and in addition can parse any message if you define message name with package in the "message" attribute.

Config example

> "parser":{
>               "type":"protobuf",
>               "parseSpec":{
>                   "format": "json",
>                   "timestampSpec":{...},
>                   "dimensionsSpec": {
>                       "dimensions":[...]
>                   }
>               },
>               "descriptor": "...",
>               **"message"**: "prototest.ProtoTestEventWithMessages"
>           },
> ....

**2.** _ProtoBufInputRowParser_ doesn't parse embedded DynamicMessage. Thus it is not possible to parse any complex message which aggregates other messages or collections of messages.

Now you can defile a deep chain access to messages and their fields using "." as a separator between parent field and child field.
Example of valid dimensions:

> "id", "description",
>           "location.country", "location.state", "location.city", "location.zipcode",
>           "income.income", "income.currency", "income.occupationType",
>           "interests.interestName", "interests.subInterestNames", "interests.interestCode.code"

Since druid supports first level multi-value columns you can get a list of values from desizered path from the collection of similar messages
Example: interests.subInterestNames will return a list of values

Please let me know if you will need more information about this PR.

### CODE REVIEW

**Comment by fjy** [comment]
@rpashuto Thanks for the contrib! Do you mind filling out druid.io/community/cla.html and we'll try to get this reviewed and merged

**Comment by rpashuto** [comment]
@fjy, i've filled out the cla.

**Comment by fjy** [comment]
@rpashuto we have some backlog preventing us from reviewing this in detail

Do you know if it is possible to actually restructure this code as a module to Druid? If so, it'll be much faster review process

**Comment by rpashuto** [comment]
@fjy I'll try to do that

**Comment by fjy** [comment]
@rpashuto some merge conflicts now, but if this can be made into a extensions-contrib module, we can get it in fairly fast

**Comment by fjy** [comment]
Removing milestone for now as this still needs more work to be made into an extensions module

**Pull request closed without merging**
