### PR TITLE
upgrade to RoaringBitmap 0.8.0 and serialise directly to ByteBuffer

### PR DESCRIPTION
**Pull request by richardstartin**

### CODE REVIEW

**Comment by richardstartin** [comment]
I doubt druid bottlnecks on serialising bitmaps, but I wrote this new method in RoaringBitmap for an application that does, and it may be useful here. Here's some quick benchmark evidence, taking a look at how long `WrappedRoaringBitmap.serialize` takes before and after the change.

```java
  @Benchmark
  public void serialize(SerializeBenchmarkState state, Blackhole bh)
  {
    state.bitmap.serialize(state.buffer);
    bh.consume(state.buffer);
    state.buffer.flip();
  }

  @State(Scope.Benchmark)
  public static class SerializeBenchmarkState
  {
    WrappedRoaringBitmap bitmap;
    ByteBuffer buffer;

    @Setup
    public void setup(BitmapIterationBenchmark state)
    {
      bitmap = new WrappedRoaringBitmap();
      Random random = ThreadLocalRandom.current();
      for (int bit = 0; bit < state.size; bit++) {
        if (random.nextDouble() < state.prob) {
          bitmap.add(bit);
        }
      }
      buffer = ByteBuffer.allocate(bitmap.getSizeInBytes());
    }
  }
```

```
8c104a115c4e08b2df60d940d6d85a7e79bef752 (incubator-druid:master)

Benchmark                           (bitmapAlgo)  (prob)   (size)  Mode  Cnt       Score       Error  Units
BitmapIterationBenchmark.serialize       roaring     0.0  1000000  avgt   10      29.110 ±     0.459  ns/op
BitmapIterationBenchmark.serialize       roaring   0.001  1000000  avgt   10   10624.144 ±   139.993  ns/op
BitmapIterationBenchmark.serialize       roaring     0.1  1000000  avgt   10  187265.856 ±  5515.013  ns/op
BitmapIterationBenchmark.serialize       roaring     0.5  1000000  avgt   10  184694.297 ±  8353.848  ns/op
BitmapIterationBenchmark.serialize       roaring    0.99  1000000  avgt   10  233570.949 ± 67602.280  ns/op
BitmapIterationBenchmark.serialize       roaring     1.0  1000000  avgt   10    1083.100 ±    38.245  ns/op



32673c121edea450b84ffef767506b60a49f4a23 (richardstartin:faster-roaring-serialize)
Benchmark                           (bitmapAlgo)  (prob)   (size)  Mode  Cnt      Score     Error  Units
BitmapIterationBenchmark.serialize       roaring     0.0  1000000  avgt   10     10.510 ±   0.182  ns/op
BitmapIterationBenchmark.serialize       roaring   0.001  1000000  avgt   10    957.783 ±  12.215  ns/op
BitmapIterationBenchmark.serialize       roaring     0.1  1000000  avgt   10  54361.198 ± 655.209  ns/op
BitmapIterationBenchmark.serialize       roaring     0.5  1000000  avgt   10  53632.341 ± 377.866  ns/op
BitmapIterationBenchmark.serialize       roaring    0.99  1000000  avgt   10  16405.135 ± 271.594  ns/op
BitmapIterationBenchmark.serialize       roaring     1.0  1000000  avgt   10    404.527 ±   3.868  ns/op
```

**Comment by lemire** [comment]
I would add that even if one does not care about the performance boost, the gains in code simplicity are very interesting.

**Comment by drcrallen** [comment]
Would it be worth keeping a stupid pool of buffers for the bitmaps to serialize into? I guess we probably don't have a good way to free the buffers later

**Comment by lemire** [comment]
> Would it be worth keeping a stupid pool of buffers for the bitmaps to serialize into?

My expectation is that this...

```
ByteBuffer buffer = ByteBuffer.allocate(bitmap.serializedSizeInBytes());
```

Is going to be pretty fast compared to doing...

```
byte[] buffer = new byte[bitmap.serializedSizeInBytes()];
```

In some of the code above, the ByteBuffer does not escape, so if escape analysis works, it may not even stress the garbage collection. In fact, it may end up  being free once the JIT compiler does it work.


A distinct issue is that these byte arrays probably get created and garbage collected all the time. 

What do you do with the byte arrays? Could you be more direct?

**Comment by richardstartin** [comment]
The underlying array is always going to get allocated, unless it's smaller than 64 elements in which case it may get scalarised, but knowing the serialisation format that just isn't going to happen. 

There might be an opportunity here for someone with more skin in the game to do some refactoring to avoid the byte[] allocation entirely. A quick glance at the code indicates that the result of `toBytes()` gets written into `WriteOutBytes`, every implementation of which delegates to a `ByteBuffer`. It should be possible to remove some of the indirection and supply the buffer directly to the bitmap, avoiding unnecessary allocations, maybe resulting in better jitted code. 

Of course, there are engineering tradeoffs and this may not actually be a performance hot spot...

**Comment by lemire** [comment]
@richardstartin What you describe looks like it might reduce the code complexity....

**Pull request merged**
