### PR TITLE
For load segment in a disk(location) randomly

### PR DESCRIPTION
**Pull request by sekingme**
Choose an available disk(location) randomly to store a segment, rather than always choose the first available disk(location). We can fully use all disks and balance all disks with this feature.

Added/modified some unit tests to support the feature. 

The code has been tested over 3 months in our production Druid environment of 108 nodes, too.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * `SegmentLoaderLocalCacheManager`
 * `SegmentLoaderLocalCacheManagerTest`

### CODE REVIEW

**Comment by clintropolis** [comment]
Hi @sekingme, it looks like there is some overlap between this PR and #8038, which adds a `locationSelectorStrategy` and includes `leastBytesUsed` and `roundRobin` implemented by `LeastBytesUsedStorageLocationSelectorStrategy` and `RoundRobinStorageLocationSelectorStrategy` provided in that PR.. I think it would make sense to hold off until that PR is merged, and instead do what you would like to achieve in this PR as a `RandomLocationSelectorStrategy` to set `locationSelectorStrategy` to `random`. 

What do you think?

**Comment by sekingme** [comment]
> Hi @sekingme, it looks like there is some overlap between this PR and #8038, which adds a `locationSelectorStrategy` and includes `leastBytesUsed` and `roundRobin` implemented by `LeastBytesUsedStorageLocationSelectorStrategy` and `RoundRobinStorageLocationSelectorStrategy` provided in that PR.. I think it would make sense to hold off until that PR is merged, and instead do what you would like to achieve in this PR as a `RandomLocationSelectorStrategy` to set `locationSelectorStrategy` to `random`.
> 
> What do you think?


Haha, sure!
PS: That PR has been stayed soooooo long~~ ^o^

**Comment by sashidhar** [comment]
Hi @sekingme, I'm working on implementing the review comments for https://github.com/apache/incubator-druid/pull/8038. Hoping to finish off soon will keep you updated on the progress. Thanks.

**Comment by sashidhar** [comment]
Hi @sekingme , PR https://github.com/apache/incubator-druid/pull/8038 is merged to master. As @clintropolis suggested you could now add your `RandomLocationSelectorStrategy` implementation. This is the interface `StorageLocationSelectorStrategy` which needs to be implemented.

**Comment by sashidhar** [comment]
@jihoonson FYI.

**Comment by sekingme** [comment]
> Hi @sekingme , PR #8038 is merged to master. As @clintropolis suggested you could now add your `RandomLocationSelectorStrategy` implementation. This is the interface `StorageLocationSelectorStrategy` which needs to be implemented.

OK, I will check and finish it later.

**Comment by sekingme** [comment]
> Hi @sekingme , PR #8038 is merged to master. As @clintropolis suggested you could now add your `RandomLocationSelectorStrategy` implementation. This is the interface `StorageLocationSelectorStrategy` which needs to be implemented.

Hi, @sashidhar @clintropolis . The implementation of this PR has already been changed according to the suggestion. Pleased check.

**Comment by sashidhar** [comment]
Cool @sekingme 👍

**Pull request merged**
