### PR TITLE
Bump Apache Thrift to 0.10.0

### PR DESCRIPTION
**Pull request by Fokko**
Bump Apache Thrift to at least 0.10.0 for now. https://github.com/apache/thrift/blob/master/CHANGES.md#0100

### Description

<hr>

This PR has:
- [x] been self-reviewed.

### CODE REVIEW

**Comment by Fokko** [comment]
Rebased onto master

**Comment by jihoonson** [comment]
+1 after CI.

LGTM and Teamcity are failing because of the missing libthrift-0.5.0-1 jar. I think we can solve this by simply updating the version of `scrooge-maven-plugin` which is using that versino of libthrift.

This PR will make Travis failed because it's not updating `licences.yaml`. I will raise a PR to fix that shortly.

**Comment by Fokko** [comment]
`scrooge-maven-plugin` is already using Thrift 0.10.0. I've rebased onto master.

**Comment by clintropolis** [comment]
>Why is this a development blocker?

The old version of `scrooge-maven-plugin` uses a super old forked version of libthrift for some reason that isn't on maven central, and seems to have recently stopped working for teamcity and lgtm CI checks, meaning no PRs are passing.

**Comment by clintropolis** [comment]
>This PR will make Travis failed because it's not updating licences.yaml.

It actually might not, the old version doesn't appear to be in `licenses.yaml`.

**Comment by Fokko** [comment]
Thanks, updating scrooge should fix the dependency on the ancient version of libthrift indeed. Jenkins is running on my fork as well: https://travis-ci.org/Fokko/druid/builds/607854795 The one on Apache is still pending due to capacity issues.

**Comment by clintropolis** [comment]
>though maybe it should be since there is a NOTICE file, https://github.com/apache/thrift/blob/master/NOTICE.

Responding to myself, but I don't think we need to worry about updating `licenses.yaml` in this PR.

**Comment by jihoonson** [comment]
The LGTM is failing with the same error even after I restarted once. Since TeamCity looks fine, I think it's an issue with LGTM (maybe it's caching something). I'll merge this PR shortly and will see other builds succeed.

**Pull request merged**
