### PR TITLE
Support LDAP authentication/authorization

### PR DESCRIPTION
**Pull request by mohammadjkhan**

### CODE REVIEW

**Comment by QiuMM** [comment]
Changed the title with a more meaningful name. #6836

**Comment by QiuMM** [comment]
@mohammadjkhan why closed?

**Comment by mohammadjkhan** [comment]
@QiuMM Because the build travis build failed. Also, it looks like I'll be making more changes. Could I know what's the process to follow if i did something wrong? This is going to be my first PR
Thanks!

**Comment by QiuMM** [comment]
@mohammadjkhan you can keep the PR and push more commits to complete it, there is no need to close it and open a new one.

**Pull request closed without merging**
