### PR TITLE
Remove unnecessary check for contains() in LoadRule

### PR DESCRIPTION
**Pull request by samarthjain**
See https://github.com/apache/incubator-druid/issues/7072

### CODE REVIEW

**Comment by fjy** [comment]
👎 This isn't a true veto, but I caution all other reviewers to not merge this without much more careful inspection of all surrounding code. There is logic in the load rules that is not immediately obvious upon first reading it but can have dramatic impacts and completely destabilize entire clusters.

**Comment by samarthjain** [comment]
> 👎 This isn't a true veto, but I caution all other reviewers to not merge this without much more careful inspection of all surrounding code. There is logic in the load rules that is not immediately obvious upon first reading it but can have dramatic impacts and completely destabilize entire clusters.

Not sure I understand the concern here. It looks fairly straightforward to me. The only caller of LoadRule#run method is DruidCoordinatorRuleRunner.

And the DruidCoordinatorRuleRunner#run method is effectively doing the contains check here
```
for (DataSegment segment : params.getAvailableSegments()) {
```

**Comment by fjy** [comment]
> > 👎 This isn't a true veto, but I caution all other reviewers to not merge this without much more careful inspection of all surrounding code. There is logic in the load rules that is not immediately obvious upon first reading it but can have dramatic impacts and completely destabilize entire clusters.
> 
> Not sure I understand the concern here. It looks fairly straightforward to me. The only caller of LoadRule#run method is DruidCoordinatorRuleRunner.
> 
> And the DruidCoordinatorRuleRunner#run method is effectively doing the contains check here
> 
> ```
> for (DataSegment segment : params.getAvailableSegments()) {
> ```

We've had so many problems with similar seemingly straightforward changes in these blocks of code that I want to be extra careful because of its impacts on clusters. I recall when writing this code that some of the checks are very important even if they don't appear to be. I just don't recall all the reasons why.

**Comment by egor-ryashin** [comment]
Looks correct.

**Comment by leventov** [comment]
Note that a similar check can *not* be removed (currently) in `DruidCoordinatorBalancer`, here:
https://github.com/apache/incubator-druid/blob/050728b11591865991591f5ae571be009cf9bbf8/server/src/main/java/org/apache/druid/server/coordinator/helper/DruidCoordinatorBalancer.java#L182-L184

Because ServerHolder's data in `toMoveFrom` and "availableSegments" originate from two different sources: `ServerInventoryView` (see [`CoordinatorHistoricalManagerRunnable `](https://github.com/apache/incubator-druid/blob/050728b11591865991591f5ae571be009cf9bbf8/server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java#L677)) and `MetadataSegmentManager` (see `DruidCoordinatorSegmentInfoLoader`) respectively.

(Perhaps it could be optimized somehow, I didn't think about that.)

So I think the check in `LoadRule` was added by analogy.

@samarthjain could you please add a comment to the check in `DruidCoordinatorBalancer` explaining this matter?

**Comment by leventov** [comment]
> @samarthjain could you please add a comment to the check in DruidCoordinatorBalancer explaining this matter?

However, I've added such a comment myself in #7185.

**Comment by leventov** [comment]
@fjy I'm going to merge this PR next Monday unless you will leave some comments.

**Comment by gianm** [comment]
I'd like to merge this now, and think it is fine to, since @fjy suggested being 'extra careful' and I think we have been. Just waiting for TC to pass successfully.

**Pull request merged**
