### PR TITLE
skip travis on doc only changes

### PR DESCRIPTION
**Pull request by clintropolis**
Following up on [a comment](https://github.com/apache/incubator-druid/pull/6045#issuecomment-408248868) in another PR I was looking into things to do to make travis better and came across [this method to skip travis tests on doc only changes]( https://github.com/facebook/react/pull/2000).

### CODE REVIEW

**Comment by gianm** [comment]
I think `examples` includes code (and we ship it in the distro) so that should still have Travis run on it.

**Comment by clintropolis** [comment]
Ah so it, does. I suppose I could ignore some of it's subfolders, maybe `examples/bin` `examples/conf` `examples/conf-quickstart` examples/quickstart`?

**Comment by jihoonson** [comment]
@clintropolis it sounds good.

**Comment by clintropolis** [comment]
reverting because this doesn't seem to work correctly

**Pull request merged**
