### PR TITLE
endpoint to delete lookup tier and remove tier on last lookup deletion

### LINKED ISSUE #4940: There is no way to delete lookup tiers
I see no endpoint that allows deletion of dynamic lookup tiers (i.e. user-defined tiers that are not the __default tier).  Please provide one or explain why no such endpoint can be provided.

### PR DESCRIPTION
**Pull request by himanshug**
Fixes #4940

### CODE REVIEW

**Comment by vogievetsky** [comment]
Hmmm, how should this interact with the lookup view in the web console? Would it make more sense for the remove lookup tier endpoint to tidy up after itself if it is removing the last lookup in a tier?

**Comment by himanshug** [comment]
@vogievetsky with this patch, on the server , a tier would automatically be deleted when last lookup in it gets deleted. so for web console, it would make sense to do so as well. Also maybe add something for calling the newly added delete tier endpoint .

**Comment by vogievetsky** [comment]
> a tier would automatically be deleted when last lookup in it gets deleted

Oh cool. That is what I was asking.

> Also maybe add something for calling the newly added delete tier endpoint .

If going forward a tier will be auto deleted when the last lookup is deleted, under what circumstances would a user want to do that? Would it bulk delete all the lookups in that tier? Or did you add it as a way to remove empty tiers that might be left behind in the current version of Druid?

**Comment by himanshug** [comment]
> Would it bulk delete all the lookups in that tier? Or did you add it as a way to remove empty tiers that might be left behind in the current version of Druid?
both :)

**Pull request merged**
