### PR TITLE
Fix Empty InDimFilter Failure

### LINKED ISSUE #6101: Druid InDimFilter Fails on Empty Values
### Use Case:
We dynamically build Druid queries by allowing the user to filter the UI. Sometimes this results in the user filtering out all options (sometimes unintentionally), and is something we want to allow for.

### Problem:
In https://github.com/apache/incubator-druid/blob/04ea3c9f8c1f5ea34b023217bd709509ace4d30d/processing/src/main/java/io/druid/query/filter/InDimFilter.java#L78
Druid fails when filtering on empty values, though I see no reason why it should since the result should just be empty. e.g. in pseudocode,

```
 mydatasource.filter(mycolumn in []) = []
```

Is there a better reason for this, or can I submit a PR to remove that restriction?

### PR DESCRIPTION
**Pull request by robertervin**
Fixes #6101 

While it may be more efficient to not process an empty filter, it is not wrong logically and should be supported for correctness.

A use case of this would be auto-filtering UIs which might happen to generate empty filters. It should be up to the application programmer to determine whether or not they want to incur that extra processing or add more complexity to their application to shortcut the request to Druid.

### CODE REVIEW

**Comment by leventov** [comment]
It's not in line with SQL (which doesn't allow empty IN clause) but it seems that this behaviour receives complains, so the change makes sense.

**Comment by gianm** [comment]
Hi @robertervin, is this patch still interesting to you? Could you please add a test?

**Comment by robertervin** [comment]
@gianm Yep I'll add a test this weekend, thanks

**Comment by robertervin** [comment]
@gianm Added a test case and updated docs to reflect now logic. Let me know if there are other places I should be concerned about testing too. 

Also the build failed with what appears to be a timeout. Could this be restarted please?

**Comment by gianm** [comment]
@robertervin I just restarted those two.

**Comment by robertervin** [comment]
@gianm I just ran the full processing test suite locally and all tests passed in ~9 min. The build keeps failing due to timeouts, so I think it might be purely a build issue. Is continuously restarting it the best way to handle this right now?

**Comment by robertervin** [comment]
@gianm Thanks for restarting the build if you did that. This should be ready for a final review.

**Comment by b-slim** [comment]
+1

**Pull request merged**
