### PR TITLE
Get correct curr_size attribute value for historical servers

### PR DESCRIPTION
**Pull request by surekhasaharan**
`sys.servers` is showing curr_size as 0 for all server types, it should get the correct size for historical server types. 
Fixed the curr_size, by getting it from `DruidServer` via `InventoryView`

### CODE REVIEW

**Comment by fjy** [comment]
@surekhasaharan which release is this for?

**Comment by fjy** [comment]
Merging given that TC is broken.

**Comment by jihoonson** [comment]
@fjy this bug was introduced in https://github.com/apache/incubator-druid/pull/7654.

**Comment by surekhasaharan** [comment]
@fjy this is for 0.16 i think.

**Pull request merged**
