### PR TITLE
Web-Console: add clipboard modal

### PR DESCRIPTION
**Pull request by mcbrewster**
Screen Shot 2019-06-26 at 11 23 19 AM

The blue clipboard has been replaced with the "more" ellipses that open a model will the full value of the cell. Additionally any occurrences of ...0 omitted.. have been fixed.  previously the omitted value was calculated by taking the length minus the max length plus 17 characters for the omitted text. This has been changed to be the max length minus 17 characters for the omitted text, because in reality only 33 characters of preview text will be shown.

### CODE REVIEW

**Comment by clintropolis** [comment]
CI failures look maybe legitmate:
https://travis-ci.org/apache/incubator-druid/jobs/550535292#L8827

**Comment by fjy** [comment]
@mcbrewster this has conflicts

**Comment by vogievetsky** [comment]
looks like legit CI failures

**Comment by vogievetsky** [comment]
You need to update the snapshots again

**Comment by vogievetsky** [comment]
awesome, thank you 👍

**Pull request merged**
