### PR TITLE
use alternative public domain text instead of lorem ipsum text in compression test

### PR DESCRIPTION
**Pull request by clintropolis**
to be unambiguous with regards to licensing, see discussion on 0.15.1 IPMC vote thread, https://lists.apache.org/thread.html/f97a3743e441747552f54dd61148366d808883e33d55cab0d5161770@%3Cgeneral.incubator.apache.org%3E

### CODE REVIEW

**Comment by gianm** [comment]
DataSketches uses the Gettysburg Address, which is in the public domain: https://github.com/apache/incubator-datasketches-memory/blob/master/src/test/resources/GettysburgAddress.txt

**Comment by vogievetsky** [comment]
There are so many public domain books out there: https://www.gutenberg.org/browse/scores/top

I think using the apache license might be not great as it might confuse someone as to the intent of that file

**Comment by vogievetsky** [comment]
Call me Ishmael. ;-)

**Comment by vogievetsky** [comment]
Nice choice.

**Pull request merged**
