### PR TITLE
handle empty sketches

### PR DESCRIPTION
**Pull request by AlexanderSaydakov**
this is to address #7486

### CODE REVIEW

**Comment by gianm** [comment]
Could you add a test for this please? (It seems like the kind of thing that's likely to get missed if the code is ever refactored, so a test is good to protect against that.)

**Comment by AlexanderSaydakov** [comment]
Could you point me to the best example of a test for such a purpose? Should it be a micro-test (minimalistic unit test) or some sort of an integration test similar to what we do now in DoublesSketchAggregatorTest where we construct a json query and run it using the AggregationTestHelper?

**Comment by gianm** [comment]
@AlexanderSaydakov I am not intimately familiar with the code, but I'd guess that a minimalistic unit test would be best. In general I prefer unit tests when feasible.

**Comment by AlexanderSaydakov** [comment]
I don't understand what happened with the inspection:
Java HotSpot(TM) 64-Bit Server VM warning: Insufficient space for shared memory file:
[22:26:11]   30896

**Comment by jon-wei** [comment]
TeamCity inspection report doesn't show any new errors in the files affected by this patch, merging

**Pull request merged**
