### PR TITLE
support NVL sql function

### LINKED ISSUE #7961: DruidSQL: there should be an NVL function that is just an alias for COALESCE
### Description

Druid SQL supports COALESCE but some [DBs call that function NVL](https://www.oracletutorial.com/oracle-comparison-functions/oracle-nvl/) also Druid's expression language [calls this function nvl](https://druid.apache.org/docs/latest/misc/math-expr.html).

### Motivation

There is nothing wrong with having aliases for functions in SQL, it might save someone a bit of confusion.

### PR DESCRIPTION
**Pull request by xueyumusic**
Fixes #7961 , support NVL sql function.
Calcite auto convert nvl to case-when-search, not using druid nvl function expr.

### CODE REVIEW

**Comment by vogievetsky** [comment]
LOL awesome! Thank you!



What is `case_searched` and `notnull` ? Neither is in http://druid.io/docs/latest/misc/math-expr.html

**Comment by xueyumusic** [comment]
Hi, @vogievetsky , `case_searched` is in math-expr.html's `General functions` section. [notnull](https://github.com/apache/incubator-druid/blob/master/core/src/main/java/org/apache/druid/math/expr/Function.java#L1607) looks not in the doc. 
Thanks.

**Comment by vogievetsky** [comment]
Great, thank you!

**Comment by gianm** [comment]
@xueyumusic could you fix the conflicts please?

**Comment by xueyumusic** [comment]
Hi, @nishantmonu51 @gianm , thank you, I updated to fix the conflict

**Pull request merged**
