### PR TITLE
support radians and degrees in sql

### PR DESCRIPTION
**Pull request by xueyumusic**
Current query math functions support toRadians and toDegrees, it could simply be exposed in sql.
The sql functions are "RADIANS" and "DEGREES", and the tests are added

### CODE REVIEW

**Comment by surekhasaharan** [comment]
@xueyumusic could you please check the test failure.

**Comment by xueyumusic** [comment]
@surekhasaharan , thans for reminding. It looks the the order of virtualColumns of this test case might be a little randoms..I will look it deeper..

**Comment by xueyumusic** [comment]
Updated, @surekhasaharan , thanks~

**Comment by surekhasaharan** [comment]
thanks @xueyumusic for quick fix.

**Pull request merged**
