### PR TITLE
Add credentials for ECS

### LINKED ISSUE #8559: Kinesis indexing service missing credentials for containers
When using the Kinesis indexing service plugin I get the following errors: 

```
2019-09-19T02:45:40,119 DEBUG [KinesisSupervisor-spade-kinesis] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from org.apache.druid.common.aws.ConfigDrivenAwsCredentialsConfigProvider@6c3ff383: Unable to load AWS credentials from druid AWSCredentialsConfig
2019-09-18 19:45:402019-09-19T02:45:40,119 DEBUG [KinesisSupervisor-spade-kinesis] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))f90c0f57b5004f3cbfb92739dc859135
2019-09-18 19:45:402019-09-19T02:45:40,119 DEBUG [KinesisSupervisor-spade-kinesis] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey)f90c0f57b5004f3cbfb92739dc859135
2019-09-18 19:45:402019-09-19T02:45:40,119 DEBUG [KinesisSupervisor-spade-kinesis] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from com.amazonaws.auth.profile.ProfileCredentialsProvider@2b0c3f9e: profile file cannot be nullf90c0f57b5004f3cbfb92739dc859135
```

I believe the plugin is failing to get ECS credentials because the configured credentials chain differs from the default SDK chain.

[Custom credentials chain](https://github.com/apache/incubator-druid/blob/eeb3dbe79d442dd805ef4483c9c417e1f9cc11a5/cloud/aws-common/src/main/java/org/apache/druid/common/aws/AWSCredentialsUtils.java#L32-L39)

[Default credentials provider AWS docs](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default)

Notice that a `ContainerCredentialsProvider` is missing from the Druid credentials chain.

Maybe it's time to replace this credentials chain with the SDK default?

### Affected Version

0.15.1

### PR DESCRIPTION
**Pull request by mitchlloyd**
Fixes #8559.

### Description

Allow Druid to fetch credentials from within an ECS container on AWS.

I added an instance of `EC2ContainerCredentialsProviderWrapper` which seems to be the fully baked way to get credentials on ECS with the SDK. I first tried adding `new ContainerCredentialsProvider()` but saw that constructor was deprecated. Despite `EC2` in the name, I believe this should work for ECS Fargate as well. I noticed [a similar change in the Hadoop project](https://github.com/apache/hadoop/pull/413).

I also noticed that the line below (`new InstanceProfileCredentialsProvider()`) was showing a deprecation warning in my editor. [The docs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/InstanceProfileCredentialsProvider.html) say that this constructor had been deprecated in favor of the `.getInstance` method on the same class.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [ ] ~added unit tests or modified existing tests to cover new code paths~.
- [ ] ~added integration tests~.
- [ ] been tested in a test Druid cluster.

I can test this change in a development Druid cluster. I noticed that there are no unit tests for this class, but unit tests don't seem like a good fit. I'd be happy to add onto any integration tests that I may have missed.

<hr>

##### Key changed/added classes in this PR
 * AWSCredentialsUtils

### CODE REVIEW

**Comment by mitchlloyd** [comment]
@vogievetsky, wondering if you could provide some guidance on any additional testing or documentation changes that would be needed here.

**Comment by clintropolis** [comment]
Hi @mitchlloyd, thanks for the contribution! 

It looks like this just passes through to the instance profile credentials, so it might be ok to not have to update any documentation since this is already mentioned in the [s3 aws authentication documentation](http://druid.apache.org/docs/latest/development/extensions-core/s3.html#s3-authentication-methods). I think [that doc](https://github.com/apache/incubator-druid/blob/master/docs/development/extensions-core/s3.md) would probably be the place to update though if you feel we should elaborate or if any of the details from the [EC2ContainerCredentialsProviderWrapper docs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/EC2ContainerCredentialsProviderWrapper.html) seem useful to include in our documentation.

**Comment by gianm** [comment]
I would definitely suggest updating the s3.md doc. There should be a new entry added between "Profile information" and "Instance profile information". The description could be something like,

> **Type:** EC2 container credentials
> **Details:** Based on environment variables `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` or `AWS_CONTAINER_CREDENTIALS_FULL_URI` as described in the [EC2ContainerCredentialsProviderWrapper documentation](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/EC2ContainerCredentialsProviderWrapper.html).

**Comment by gianm** [comment]
I don't think tests are needed for this patch; they would be nice, but we don't currently have a good way to test the provider chain, and this patch doesn't need to be the place to add that testing ability.

I am good to merge this patch after the doc update I mentioned above. Thanks for the contribution @mitchlloyd!

**Comment by mitchlloyd** [comment]
I updated the documentation in s3.md doc. Note that I changed the suggested wording slightly. It seems that `EC2ContainerCredentials` is a misleading name. The JavaScript SDK has a better name for this: [ECSCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ECSCredentials.html). Really this is all about using ECS and this authentication method should work with ECS configured with EC2 instances and ECS configured with Fargate instances. 

With that in mind [I made sure to mention ECS](https://github.com/apache/incubator-druid/pull/8651/commits/752cd6df3d71e0d7f1675b628969354d8d911940).

**Comment by clintropolis** [comment]
Ah, it looks like this PR is failing the spellcheck which isn't so smart unfortunately :cry:, https://travis-ci.org/apache/incubator-druid/jobs/596731393#L274

You can add entries for the things it is flagging to this file https://github.com/apache/incubator-druid/blob/master/website/.spelling

**Comment by mitchlloyd** [comment]
Finished a test. Before the patch I see these logs on ECS:

```
2019-10-11T19:47:27,671 DEBUG [KinesisSupervisor-spade-kinesis] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from org.apache.druid.common.aws.ConfigDrivenAwsCredentialsConfigProvider@278b2493: Unable to load AWS credentials from druid AWSCredentialsConfig
2019-10-11T19:47:27,673 DEBUG [KinesisSupervisor-spade-kinesis] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from org.apache.druid.common.aws.LazyFileSessionCredentialsProvider@3615d336: cannot refresh AWS credentials
2019-10-11T19:47:27,673 DEBUG [KinesisSupervisor-spade-kinesis] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
2019-10-11T19:47:27,673 DEBUG [KinesisSupervisor-spade-kinesis] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey)
2019-10-11T19:47:27,674 DEBUG [KinesisSupervisor-spade-kinesis] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from com.amazonaws.auth.profile.ProfileCredentialsProvider@749c1076: profile file cannot be null
2019-10-11T19:47:29,684 DEBUG [KinesisSupervisor-spade-kinesis] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from com.amazonaws.auth.InstanceProfileCredentialsProvider@f21c0fd: Unable to load credentials from service endpoint
java.lang.RuntimeException: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
```

No tasks can start.

After the patch I see

```
2019-10-11T21:00:13,848 DEBUG [task-runner-0-priority-0] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from org.apache.druid.common.aws.ConfigDrivenAwsCredentialsConfigProvider@673ec5ca: Unable to load AWS credentials from druid AWSCredentialsConfig
2019-10-11T21:00:13,850 DEBUG [task-runner-0-priority-0] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from org.apache.druid.common.aws.LazyFileSessionCredentialsProvider@1c2e9c96: cannot refresh AWS credentials
2019-10-11T21:00:13,850 DEBUG [task-runner-0-priority-0] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
2019-10-11T21:00:13,850 DEBUG [task-runner-0-priority-0] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey)
2019-10-11T21:00:13,852 DEBUG [task-runner-0-priority-0] com.amazonaws.auth.AWSCredentialsProviderChain - Unable to load credentials from com.amazonaws.auth.profile.ProfileCredentialsProvider@505d97d9: profile file cannot be null
```

And after that tasks successfully run.

I'll update the spelling config.

**Comment by mitchlloyd** [comment]
AFAICT this is a stalled step in the build. Maybe someone with access could just restart that part?

**Comment by jon-wei** [comment]
I restarted that stalled test

**Pull request merged**
