### PR TITLE
Add rebalance strategy for RandomBalancerStrategy

### PR DESCRIPTION
**Pull request by elloooooo**
Now when users use the `RandomBalancerStrategy` at Coordinator, there is no implementation to rebalance the segments which alreay exist on the Historical server. For example, if a new historical node is add to a druid cluster which already has much data on historical nodes, the used percentage of new historical node willl be much less than avg used percentage of the whole cluster for a long time. So I add an implementation for `RandomBalancerStrategy` to rebalance the data.

The basic idea is compare the used percentage of every historical node with  avg used percentage of whole cluster. When the difference is more than a threshold which can be configured as a dynamic configuration and the server is not serving the target segment, then the server will be one of the candidates to move the segment to. At last pick one server from the candidates randomly and move the segment to it.

The threshold is default 5% and must bigger than 1%.

### CODE REVIEW

**Comment by jihoonson** [comment]
Hi @elloooooo, I wonder there's any production use case where `RandomBalancerStrategy` is used. Are you using it? If so, would you please give us some context why it's better than others like `CostBalancerStrategy` in your use case?

**Comment by elloooooo** [comment]
@jihoonson The main reason for using `RandomBalancerStrategy` is the performance 
 of `CostBalancerStrategy` or `CachedCostBalancerStrategy` is not good enough when we now have 1,500,000+ segments. They take too much time for calculating the cost of every two segments and lead handoff stuck.

**Comment by clintropolis** [comment]
Hmm, I think at least `CachedCostBalancerStrategy` should be able to handle that many segments and many more, however it I know it is possible to make this not true via coordinator configuration. I would be interested in how your coordinator is tuned in the case where it is causing stuck handoff, like what are settings for max segments to move, etc? Additional cluster details such as number of historical nodes, type of deep storage, type of segment loading, etc, would be interesting as well if you're willing to share.

Using the `CostBalancerStrategy` or some variant of it should provide for much higher query performance because it takes into account segment sizes, datasources, intervals and space on historical servers and tries to maximize query fan out opportunity at an datasource/interval local scale. This is definitely expensive to compute, and it is i think biased, in large clusters at least, towards having smallish values of max segments to move in order to slowly converge the cluster to a balanced and reasonably query optimized state, but should minimize the amount of queries that get bottlenecked because of segments not being adequately spread out across the cluster.

That said, if for some reason `CachingCostBalancerStrategy` doesn't fit your use case, I don't think these changes are quite appropriate to add to `RandomBalancerStrategy`. I believe these changes make it behave much less randomly as it would now balance on storage capacity usage,  as far as I understand this PR. Rather, I think it would be more sensible to add a new balancer strategy that implements this functionality instead, maybe call it `DiskThresholdBalancerStrategy`. However, I think on the query side balancing like this is not going to be a great experience in terms of query speed, since nothing will prevent or actively try to avoid load being concentrated in hot spots.

**Comment by elloooooo** [comment]
@clintropolis Hi~ I have used `CachedCostBalancerStrategy` in our druid cluster which has 39 historical nodes and  2.6M segment(includes replicas). It assigns 150+ segments per minute. I set maxSegmentsToMove 30. Now it works fine. 

By the way, I still think this PR should be included to complete the `RandomBalancerStrategy`.

**Comment by elloooooo** [comment]
@gianm Would you please review this PR? What do you think about it?

**Comment by gianm** [comment]
Hi @elloooooo, I think I agree with @clintropolis - it makes more sense to me for the random balancer to be as close to totally random as possible. More 'smart' approaches make more sense to me in other strategy classes. It's good to hear you got the caching cost balancer working well in your case. Beyond what you already did, setting balancer threads higher could speed it up more.

It looks like we won't merge this change, but, thanks for the discussion it sparked.

If you have any more issues with balancing please do bring them to the attention of the community!

**Comment by elloooooo** [comment]
@gianm Thank you for your reply. Don't you think the missing of ability of segment rebalance makes the `RandomBalancerStrategy` incomplete or there is actually no need for `RandomBalancerStrategy`? 

By the way,  I found a issue using `cachingCostBalancer` described in  #6624. It seems  `cachingCostBalancer` can't perform well in case the new historicals added to a cluster which alreay has mang segment.

**Pull request closed without merging**
