### PR TITLE
remove Kafka eight module

### PR DESCRIPTION
**Pull request by b-slim**
I think this module is not used anymore (am not sure if it was really used), it has some outdated dependencies and takes out build resources for no reason.
Am suggestion removing it.

---
This change is [Reviewable](https://reviewable.io/reviews/druid-io/druid/5841)

### CODE REVIEW

**Comment by b-slim** [comment]
CC @fjy

**Comment by freakyzoidberg** [comment]
Hello, although we wouldn't be impacted by this removal, 
We use a slightly modified version of this for Kafka 10, which I guess we could contribute back if you want.

**Comment by b-slim** [comment]
@freakyzoidberg contribution is more than welcome, you want to send a PR to add your module as part of contrib modules?

**Comment by jihoonson** [comment]
Please check the CI failure.

**Comment by jon-wei** [comment]
I'm not sure if we should remove this (or maybe keep those firehose implementations in sync with the kafka version used by kafka-indexing-service, is that worth the effort?).

If we do get rid of it, we should probably also remove http://druid.io/docs/latest/development/extensions-contrib/kafka-simple.html and take out the docs for both extensions as well

**Pull request closed without merging**
