### PR TITLE
Ignore the web-console/build directory

### PR DESCRIPTION
**Pull request by asdf2014**
### Description

Ignore the web-console/build directory.

<hr>

This PR has:
- [x] been self-reviewed.
   - [x] using the [concurrency checklist](https://github.com/apache/incubator-druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

<hr>

### CODE REVIEW

**Comment by gianm** [comment]
The `web-console` directory has its own `.gitignore`. Maybe add it to that. What generates this `build` directory, btw?

**Comment by asdf2014** [comment]
@gianm Sure, it has been moved to the .gitignore file in web-console. I think the `build` directory is generated by TypeScript's `tsc` command, and the specific path is specified by the `outDir` configuration in `tsconfig.json`.

**Comment by vogievetsky** [comment]
While there is an `outDir: build` set in the tsconfig it should never be used. That setting could probably be removed. TypeScript is only used via the webpack ts-loader. You should not need to run `tsc` directly.
We should clean up the tsconfig. I don't think git ignoring `build` is a good idea as it just hides the real problem - which is we should never be writing to that dir.

**Comment by gianm** [comment]
@vogievetsky are you suggesting doing a different patch that adjusts the `tsconfig.json` file somehow?

**Comment by asdf2014** [comment]
> While there is an `outDir: build` set in the tsconfig it should never be used. That setting could probably be removed. TypeScript is only used via the webpack ts-loader. You should not need to run `tsc` directly.
> We should clean up the tsconfig. I don't think git ignoring `build` is a good idea as it just hides the real problem - which is we should never be writing to that dir.

@vogievetsky In fact, I have never manually executed the `tsc` command. I don't know why, after opening the project in the IDE for a while, the `build` directory will still be created automatically. I will close this. BTW, maybe the `"run": "./script/run"` script in `package.json` also is not necessary. If you can, please help delete it.

**Comment by vogievetsky** [comment]
I will clean up the build artifacts ASAP

**Pull request closed without merging**
