### PR TITLE
discard filter when processing subtotalsSpec

### PR DESCRIPTION
**Pull request by himanshug**
Backports #7827

 Due to the user request in https://github.com/apache/incubator-druid/issues/7820#issuecomment-507155898

### CODE REVIEW

**Comment by himanshug** [comment]
that said, I know we are pretty far in the 0.15.0 release process . We can probably merge this and let it be part of RC-3 if we make that for any reason.

**Comment by fjy** [comment]
@himanshug do we need to backport this or can it just go out in 0.16?

**Comment by himanshug** [comment]
I personally don't need it in 0.15.0, backported it because of https://github.com/apache/incubator-druid/issues/7820#issuecomment-507155898
we can leave it out unless we do an rc-3 for some additional reason

**Comment by fjy** [comment]
@himanshug 0.15.0 stable has already been released

**Comment by himanshug** [comment]
duh , I missed the announcement I guess :)

**Pull request closed without merging**
