### PR TITLE
[for 0.12.x] general exactly count distinct support in Druid

### PR DESCRIPTION
**Pull request by pzhdfy**
The detailed design and discussion is in issue https://github.com/apache/incubator-druid/issues/6716
**Target**
support general exactly count distinct in Druid

**Attention**
the pr is for branch 0.12.x,  I will make another pr for master(0.14+)

**Usage**
1. configure to use extension druid-uniq: druid.extensions.loadList=[...,"druid-uniq"]
2. define a unique metric in  metricsSpec at Ingestion time
 ` "metricsSpec": [
                {
                    "type": "count",
                    "name": "count"
                },
                {
                    "name": "author_id_distinct",
                    "type": "unique",
                    "fieldName": "author_id"
                }
            ],`
3. define a unique metric in  aggregations at query time
`{
  "queryType": "timeseries",
  "postAggregations": [],
  "granularity": "ALL",
  "dataSource": "druid_hadoop_task_example",
  "intervals": "2018-04-24T00:00:00+08:00/2018-04-26T00:00:00+08:00",
  "aggregations": [
    {
      "name": "count",
      "type": "count"
    },
    {
      "name": "author_id_distinct",
      "type": "unique",
      "fieldName": "author_id_distinct"
    }
  ]
}`

### CODE REVIEW

**Comment by clintropolis** [comment]
Hi @pzhdfy thanks for the proposal and PR! For new features like this, we generally only will merge into the master branch, so I think we should close this PR to focus on #7594.

**Comment by pzhdfy** [comment]
> Hi @pzhdfy thanks for the proposal and PR! For new features like this, we generally only will merge into the master branch, so I think we should close this PR to focus on #7594.

I think so. I will close this PR

**Comment by wangxiaobaidu11** [comment]
@pzhdfy hi，I use https://github.com/pzhdfy/incubator-druid/tree/0.12.3-count-distinct code to run a  task of hadoop index, but it occurs an error that lead to the failure of importing data source
`2019-10-24 16:37:18.641 INFO [task-runner-0-priority-0] org.apache.hadoop.mapreduce.Job - Task Id : attempt_1570502169946_3012_m_000000_0, Status : FAILED
Error: io.druid.java.util.common.RE: Failure on row[{"time":"2015-09-12T01:35:41.418Z","channel":"#es.wikipedia","cityName":"AsunciÃ³n","comment":"/* Puntaje acumulado */","countryIsoCode":"PY","countryName":"Paraguay","isAnonymous":true,"isMinor":false,"isNew":false,"isRobot":false,"isUnpatrolled":false,"metroCode":null,"namespace":"Main","page":"Torneo Clausura 2015 (Paraguay)","regionIsoCode":"ASU","regionName":"Asuncion","user":"190.23.68.121","delta":1,"added":1,"deleted":0}]
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:93)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1698)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.lang.IllegalArgumentException: Value : AsunciÃ³n not exists
	at org.apache.kylin.common.util.Dictionary.getIdFromValue(Dictionary.java:107)
	at org.apache.kylin.common.util.Dictionary.getIdFromValue(Dictionary.java:85)
	at io.druid.segment.incremental.IncrementalIndex$1InputRowDictWrap.getDimension(IncrementalIndex.java:180)
	at io.druid.query.aggregation.unique.RoaringBitmapComplexMetricSerde$1.extractValue(RoaringBitmapComplexMetricSerde.java:70)
	at io.druid.query.aggregation.unique.RoaringBitmapComplexMetricSerde$1.extractValue(RoaringBitmapComplexMetricSerde.java:52)
	at io.druid.segment.incremental.IncrementalIndex$1IncrementalIndexInputRowColumnSelectorFactory$1.getObject(IncrementalIndex.java:264)
	at io.druid.query.aggregation.unique.UniqueBuildAggregator.aggregate(UniqueBuildAggregator.java:53)
	at io.druid.indexer.InputRowSerde.toBytes(InputRowSerde.java:281)
	at io.druid.indexer.IndexGeneratorJob$IndexGeneratorMapper.innerMap(IndexGeneratorJob.java:371)
	at io.druid.indexer.HadoopDruidIndexerMapper.map(HadoopDruidIndexerMapper.java:88)
	... 8 more`

**Comment by wangxiaobaidu11** [comment]
@pzhdfy  I am using ’unique‘ accurate deduplication method and groupby native query, but the obtained result is not accurate. Groupby does not support unqiue, right?

**Comment by pzhdfy** [comment]
all other bug fix is added to the pr for master : https://github.com/apache/incubator-druid/pull/7594

**Pull request closed without merging**
