### PR TITLE
some more doc improvements

### PR DESCRIPTION
**Pull request by fjy**

### CODE REVIEW

**Comment by fjy** [comment]
@jihoonson can we backport this?

**Comment by jihoonson** [comment]
Doc changes don't have to be backported. They will be applied to the latest doc anyway.

**Comment by fjy** [comment]
@jihoonson Are we releasing docs from master? I don't understand why it doesnt require backporting

**Comment by gianm** [comment]
They generally would need to be backported since we release docs from branches, not master. (Docs from master would be super confusing since they would describe unreleased features)

**Comment by jihoonson** [comment]
Sorry, I was confused. Will backport tomorrow.

**Pull request merged**
