### PR TITLE
Remove JDK 7 from build documentation.

### LINKED ISSUE #6030: "Build from Source" page states an outdated JDK version 7
[Copied from [website issue #470](https://github.com/druid-io/druid-io.github.io/issues/470)]

Problem:
The documentation page [Build from Source](http://druid.io/docs/latest/development/build.html) states the following:

`Building Druid requires the following: - JDK 7 or JDK 8`

While in fact Druid mandates JDK 8 since version 0.10.0 (as evident in Druid pr #3914 by @gianm).

Solution:
Remove the text "JDK 7 or ".

### PR DESCRIPTION
**Pull request by yurmix**
Fixes #6030

### CODE REVIEW

**Comment by jihoonson** [comment]
Ah, great! Would you fill out our CLA [here](http://druid.io/community/cla.html)?

Also, if you can change the PR comment to be start with `Fixes #6030`, the issue #6030 is automatically closed when this PR is merged. See https://help.github.com/articles/closing-issues-using-keywords/ for more details.

**Comment by yurmix** [comment]
@jihoonson Now that the project is under Apache, shouldn't it be [Apache ICLA](https://www.apache.org/licenses/icla.pdf)?
If so, I also believe this CLA link should be updated (possibly in a separate PR 😄).

**Comment by yurmix** [comment]
@jihoonson Thank you for helping with my first pr!
I have submitted one to Apache and it should be available to Druid PMCs.

**Comment by jihoonson** [comment]
@yurmix thanks!

**Pull request merged**
