### PR TITLE
[Backport] Coordinator fix balance to try to move max segments instead of up to max segments

### PR DESCRIPTION
**Pull request by jihoonson**
Backport of #5927 to 0.12.2.

### CODE REVIEW

**Comment by drcrallen** [comment]
oh noes, I don't have privileges to restart specific travis tests anymore

**Comment by jihoonson** [comment]
@drcrallen thanks for checking. I restarted. 

It looks that only some committers have been added to the Apache Druid committers of Github. Did you set your Gitbox account?

**Comment by gianm** [comment]
@drcrallen you should be able to if you go through GitBox setup: https://gitbox.apache.org/setup/

**Comment by gianm** [comment]
@jihoonson, that sounds good, let's move #5927 outside of 0.12.2.

**Pull request closed without merging**
