### PR TITLE
Prohibit LinkedList

### PR DESCRIPTION
**Pull request by leventov**
All use cases for LinkedList are covered by ArrayList and ArrayDeque, which are better options.

### CODE REVIEW

**Comment by fjy** [comment]
👎 I don't see why this refactor is required or the benefits it provides

**Comment by leventov** [comment]
@fjy it protects the codebase from introducing suboptimal code due to inattention or ignorance. It seems to me that there are no such cases in the codebase right now (all places where LinkedList is removed seem to not be important for efficiency), but this is a lucky accident.

Many refactorings are not *required* but they make supporting the codebase easier.

**Comment by leventov** [comment]
@fjy could you please respond

**Comment by gianm** [comment]
@fjy is your -1 intended as a "veto" in the ASF sense (https://www.apache.org/foundation/voting.html)?

> A code-modification proposal may be stopped dead in its tracks by a -1 vote by a qualified voter. This constitutes a veto, and it cannot be overruled nor overridden by anyone. Vetos stand until and unless withdrawn by their casters.
>
>To prevent vetos from being used capriciously, they must be accompanied by a technical justification showing why the change is bad (opens a security exposure, negatively affects performance, etc. ). A veto without a justification is invalid and has no weight.

If so, please lay out the technical justification as to why you are vetoing this change. If not, please make it clear that you did not actually intend to veto, and this change can go forward if someone else +1s it.

**Comment by fjy** [comment]
I'll change my vote to 0-. I'm not going veto the PR but I also see almost no benefit in it either.

**Comment by leventov** [comment]
@jon-wei thanks

**Comment by SEKIRO-J** [comment]
@leventov  Sometime we may want to both operate on `null values` and `O(1) pop`, neither `ArrayList` nor `ArrayDeque` can do it.

**Comment by jihoonson** [comment]
@SEKIRO-J the thing is, iterating on the linked list is expensive because it's iterating through pointers. Even though the time complexity of remove() is O(1), iteration is the most popular operation for the list. I think prohibiting using LinkedList by default is to make you sure that you really need to use it and what is the benefit of using it.

**Comment by SEKIRO-J** [comment]
@jihoonson gotcha

**Pull request merged**
