### PR TITLE
fix circular reference in moving average query

### LINKED ISSUE #7999: Druid moving average query results in circular reference error
Moving average query extension results in circular references.

### Affected Version

0.15.0-incubating

### Description

- The error message or stack traces encountered. 
When running the broker with the contrib extension `moving-average-query` following error occurs:
```
2019-06-30T09:14:03,832 ERROR [main] org.apache.druid.cli.CliBroker - Error when starting up.  Failing.
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.IllegalStateException: This is a proxy used to support circular references. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.
  at org.apache.druid.client.CachingClusteredClient.<init>(CachingClusteredClient.java:115)
  at org.apache.druid.cli.CliBroker.lambda$getModules$0(CliBroker.java:94) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliBroker$$Lambda$8/1493042329)
  while locating org.apache.druid.client.CachingClusteredClient
    for the 2nd parameter of org.apache.druid.server.ClientQuerySegmentWalker.<init>(ClientQuerySegmentWalker.java:68)
  while locating org.apache.druid.server.ClientQuerySegmentWalker
  at org.apache.druid.cli.CliBroker.lambda$getModules$0(CliBroker.java:107) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> org.apache.druid.cli.CliBroker$$Lambda$8/1493042329)
  while locating org.apache.druid.query.QuerySegmentWalker
  at org.apache.druid.query.movingaverage.MovingAverageQueryToolChest.<init>(MovingAverageQueryToolChest.java:61)
  at org.apache.druid.query.movingaverage.MovingAverageQueryModule.configure(MovingAverageQueryModule.java:48) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.movingaverage.MovingAverageQueryModule)
  while locating org.apache.druid.query.movingaverage.MovingAverageQueryToolChest
  while locating org.apache.druid.query.QueryToolChest annotated with @com.google.inject.multibindings.Element(setName=,uniqueId=136, type=MAPBINDER, keyType=java.lang.Class<? extends org.apache.druid.query.Query>)
  at org.apache.druid.guice.DruidBinders.queryToolChestBinder(DruidBinders.java:47) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.movingaverage.MovingAverageQueryModule -> com.google.inject.multibindings.MapBinder$RealMapBinder)
  while locating java.util.Map<java.lang.Class<? extends org.apache.druid.query.Query>, org.apache.druid.query.QueryToolChest>
    for the 1st parameter of org.apache.druid.query.MapQueryToolChestWarehouse.<init>(MapQueryToolChestWarehouse.java:35)
  while locating org.apache.druid.query.MapQueryToolChestWarehouse
  while locating org.apache.druid.query.QueryToolChestWarehouse
    for the 1st parameter of org.apache.druid.client.BrokerServerView.<init>(BrokerServerView.java:98)
  at org.apache.druid.client.BrokerServerView.class(BrokerServerView.java:63)
  while locating org.apache.druid.client.BrokerServerView

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1028) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050) ~[guice-4.1.0.jar:?]
	at org.apache.druid.guice.LifecycleModule$2.start(LifecycleModule.java:138) ~[druid-core-0.15.0-incubating.jar:0.15.0-incubating]
	at org.apache.druid.cli.GuiceRunnable.initLifecycle(GuiceRunnable.java:106) [druid-services-0.15.0-incubating.jar:0.15.0-incubating]
	at org.apache.druid.cli.ServerRunnable.run(ServerRunnable.java:57) [druid-services-0.15.0-incubating.jar:0.15.0-incubating]
	at org.apache.druid.cli.Main.main(Main.java:118) [druid-services-0.15.0-incubating.jar:0.15.0-incubating]
Caused by: java.lang.IllegalStateException: This is a proxy used to support circular references. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[guava-16.0.1.jar:?]
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:36) ~[guice-4.1.0.jar:?]
	at com.sun.proxy.$Proxy88.registerSegmentCallback(Unknown Source) ~[?:?]
	at org.apache.druid.client.CachingClusteredClient.<init>(CachingClusteredClient.java:131) ~[druid-server-0.15.0-incubating.jar:0.15.0-incubating]
	at org.apache.druid.client.CachingClusteredClient$$FastClassByGuice$$bc7211e6.newInstance(<generated>) ~[druid-server-0.15.0-incubating.jar:0.15.0-incubating]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:110) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:56) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.1.0.jar:?]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015) ~[guice-4.1.0.jar:?]
	at org.apache.druid.query.movingaverage.MovingAverageQueryToolChest.<init>(MovingAverageQueryToolChest.java:63) ~[?:?]
	at org.apache.druid.query.movingaverage.MovingAverageQueryToolChest$$FastClassByGuice$$567de849.newInstance(<generated>) ~[?:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[guice-4.1.0.jar:?]
```

- Any debugging that you have already done
As commented here: https://github.com/apache/incubator-druid/pull/6430#discussion_r260118600

- version
mvn --version
```
bash-4.4# mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T18:33:14Z)
Maven home: /usr/share/java/maven-3
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: /opt/jdk1.8.0_202/jre
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.9.125-linuxkit", arch: "amd64", family: "unix"
```

@yurmix or @jihoonson any of you know what happens here or what I need to do?

### PR DESCRIPTION
**Pull request by yurmix**
Fixes #7999.
Contributed by @ccl0326.

### CODE REVIEW

**Comment by yurmix** [comment]
@ccl0326 thank you for your contribution! I have verified that this fixes the issue.
I have taken the liberty to create a pull request so it will be ready for 0.15.1, but if you prefer, I can close this one and you can create a separate pull request.

**Comment by clintropolis** [comment]
This appears to partially fix the issue in my testing, at least in terms of the broker being unable to start. 

However, there are some additional difficulties to use this extension. The middle-manager is unable to load this extension, it explodes on startup with a similar:

```
Exception in thread "main" java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.apache.druid.query.QuerySegmentWalker was bound.
  while locating com.google.inject.Provider<org.apache.druid.query.QuerySegmentWalker>
    for the 1st parameter of org.apache.druid.query.movingaverage.MovingAverageQueryToolChest.<init>(MovingAverageQueryToolChest.java:62)
  at org.apache.druid.query.movingaverage.MovingAverageQueryModule.configure(MovingAverageQueryModule.java:48) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.movingaverage.MovingAverageQueryModule)

2) No implementation for org.apache.druid.server.log.RequestLogger was bound.
  while locating org.apache.druid.server.log.RequestLogger
    for the 2nd parameter of org.apache.druid.query.movingaverage.MovingAverageQueryToolChest.<init>(MovingAverageQueryToolChest.java:62)
  at org.apache.druid.query.movingaverage.MovingAverageQueryModule.configure(MovingAverageQueryModule.java:48) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.movingaverage.MovingAverageQueryModule)
```

so `druid.indexer.fork.property.druid.extensions.loadList` must be set to allow the peons to load a different set of extensions than the middle-manager, which isn't so big of a deal imo. The peon tasks for kafka indexing service did appear to startup and load the extension correctly when I did this.

More problematic, is the router, which is also unable to load this extension:

```
Exception in thread "main" java.lang.RuntimeException: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for org.apache.druid.query.QuerySegmentWalker was bound.
  while locating com.google.inject.Provider<org.apache.druid.query.QuerySegmentWalker>
    for the 1st parameter of org.apache.druid.query.movingaverage.MovingAverageQueryToolChest.<init>(MovingAverageQueryToolChest.java:62)
  at org.apache.druid.query.movingaverage.MovingAverageQueryModule.configure(MovingAverageQueryModule.java:48) (via modules: com.google.inject.util.Modules$OverrideModule -> org.apache.druid.query.movingaverage.MovingAverageQueryModule)
```

because without the extension loaded, the router is unable to perform serde on the query making any queries that use this extension unable to use the router if it's not loaded:

Screen Shot 2019-07-29 at 8 24 52 PM

I'm unsure how to resolve this situation, i guess the router could inject null as a segment walker since none of this stuff will be called, it just needs the types to do serde, but that also seems sort of lame? Not sure what is best to do.

**Comment by clintropolis** [comment]
I think because of the above reason, and because 0.16.0 is right around the corner, I am going to go ahead and make `druid-0.15.1-incubating-rc1` without this patch.

**Comment by yurmix** [comment]
@clintropolis were the only issues found are on services other than the broker? I tested it on the broker and it did work for me as well.
Please notice that as the extension's documentation states, this is supposed to be loaded on the broker only:
_To use this extension, make sure to load druid-moving-average-query only to the Broker._
 it shouldn't run on middle manager. I know other extensions have such guidelines (i.e. materialized-view).
I think since the fix is isolated to this extension and it doesn't add any features, but fix a blocking bug, it would be a good candidate for 0.15.1.

**Comment by clintropolis** [comment]
>@clintropolis were the only issues found are on services other than the broker?
If so, this is because it is purpusfully compatible only with the Broker, and the documentation states so:
To use this extension, make sure to load druid-moving-average-query only to the Broker.
I know other extensions have such guidelines (i.e. materialized-view).

>I think since the fix solves a blocking bug and doesn't add any behavior change, it would be a good candidate for a minor release. also, the change is isolated to the extension code.

I guess it is true the docs mention that only the broker is supported, I'll admit I am unfamiliar with this extension 😅. The docs probably should be updated to mention that it will not work if you query through a router at some point in the future (doesn't need to be this PR).

I did just finish building an rc1 tag... but since I didn't push anything yet I will go ahead and +1 and do a backport once this is merged.

**Comment by yurmix** [comment]
> I guess it is true the docs mention that only the broker is supported, I'll admit I am unfamiliar with this extension 😅. The docs probably should be updated to mention that it will not work if you query through a router at some point in the future (doesn't need to be this PR).
Thank you!
I will see what can I do in the future to make the extension load on at least all services in the Query server.

**Comment by lamber-ken** [comment]
This issus still exist in 0.17.0
image

**Pull request merged**
