### PR TITLE
Update LICENSE and NOTICE files

### PR DESCRIPTION
**Pull request by jon-wei**
Updates the LICENSE and NOTICE files in preparation for the next release.

Notes:
- At one point we included a modified TestNG which was mentioned in our old NOTICE file. However, this was removed in https://github.com/apache/incubator-druid/pull/5165, so I have removed references to that in LICENSE.
- We previously had a dependency on https://github.com/typetools/checker-framework introduced by https://github.com/apache/incubator-druid/pull/6662. The main project is GPL licensed, but the annotations it provides are MIT licensed. We only use annotations from this project, so this PR changes the dependency to `checker-qual` (just the annotations).
- Helper scripts for retrieving dependency info have been added to docs/_bin
- The LICENSE and NOTICE files are split into source-only and binary distribution versions, with associated packaging changes.
- Bundled licenses are stored in the licenses/src directory for source-level inclusions, and licenses/bin for binary-only dependencies
- The binary distribution now includes the README.md file along with the contents of a new LABELS.md file appended, used to hold licensing labels for Category B licenses (http://www.apache.org/legal/resolved.html#what-can-we-maybe-include-in-an-asf-project-category-b). 

I am using the information at https://github.com/justinmclean/ApacheWombat as a reference for the process.

### CODE REVIEW

**Comment by jon-wei** [comment]
marking WIP, some of the "license files" (pulled from node dependencies in web-console using a script) are not actually license files, will need to update those

**Comment by clintropolis** [comment]
I think the `licenses/` folder needs to be excluded from rat check 🙃

**Comment by jon-wei** [comment]
We are still working with Apache Legal to resolve the Blueprint dependency questions, but this PR is ready for review otherwise.

**Comment by gianm** [comment]
It looks like one of the new files needs to be excluded:

```
[WARNING] Files with unapproved licenses:
  LABELS.md
```

Also, in light of #7139 the comment https://github.com/apache/incubator-druid/pull/7026#issuecomment-466612169 should be resolved, at least for now.

**Comment by jon-wei** [comment]
I've updated this to reflect the licenses after the Blueprint downgrade patch

**Comment by jon-wei** [comment]
@clintropolis @gianm Thanks for the review, I'll update this area with more documentation/automation for future release managers after 0.14.0.

**Pull request merged**
