### PR TITLE
Fix NPE at io.druid.cli.CliInternalHadoopIndexer (fixes #6673)

### LINKED ISSUE #6673: NPE at io.druid.cli.CliInternalHadoopIndexer
> 2018-11-28T05:47:02,778 ERROR [main] io.druid.cli.CliHadoopIndexer - failure!!!!
> java.lang.reflect.InvocationTargetException
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_162]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_162]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_162]
>         at io.druid.cli.CliHadoopIndexer.run(CliHadoopIndexer.java:117) [druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.Main.main(Main.java:116) [druid-services-0.12.3.jar:0.12.3]
> Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:
> 
> 1) An exception was caught and reported. Message: null
>   at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198)
> 
> 2) Binding to null instances is not allowed. Use toProvider(Providers.of(null)) if this is your intended behaviour.
>   at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:95) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliInternalHadoopIndexer$1)
> 
> 3) Binding to null instances is not allowed. Use toProvider(Providers.of(null)) if this is your intended behaviour.
>   at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:95) (via modules: com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliInternalHadoopIndexer$1)
> 
> 4) Binding to null instances is not allowed. Use toProvider(Providers.of(null)) if this is your intended behaviour.
>   at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:96)
> 
> 5) Could not find a suitable constructor in io.druid.metadata.MetadataStorageTablesConfig. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
>   at io.druid.metadata.MetadataStorageTablesConfig.class(MetadataStorageTablesConfig.java:35)
>   at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:97) (via modules: com.google.inject.util.Modules$OverrideModule -> com.google.inject.util.Modules$OverrideModule -> io.druid.cli.CliInternalHadoopIndexer$1)
> 
> 5 errors
>         at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470) ~[guice-4.1.0.jar:?]
>         at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155) ~[guice-4.1.0.jar:?]
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:99) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.1.0.jar:?]
>         at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:403) ~[druid-server-0.12.3.jar:0.12.3]
>         at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:62) ~[druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.CliInternalHadoopIndexer.run(CliInternalHadoopIndexer.java:110) ~[druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.Main.main(Main.java:116) ~[druid-services-0.12.3.jar:0.12.3]
>         ... 6 more
> Caused by: java.lang.NullPointerException
>         at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:97) ~[druid-services-0.12.3.jar:0.12.3]
>         at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.1.0.jar:?]
>         at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.1.0.jar:?]
>         at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198) ~[guice-4.1.0.jar:?]
>         at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.1.0.jar:?]
>         at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.1.0.jar:?]
>         at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.1.0.jar:?]
>         at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177) ~[guice-4.1.0.jar:?]
>         at com.google.inject.AbstractModule.configure(AbstractModule.java:62) ~[guice-4.1.0.jar:?]
>         at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.1.0.jar:?]
>         at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.1.0.jar:?]
>         at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138) ~[guice-4.1.0.jar:?]
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:99) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:73) ~[guice-4.1.0.jar:?]
>         at com.google.inject.Guice.createInjector(Guice.java:62) ~[guice-4.1.0.jar:?]
>         at io.druid.initialization.Initialization.makeInjectorWithModules(Initialization.java:403) ~[druid-server-0.12.3.jar:0.12.3]
>         at io.druid.cli.GuiceRunnable.makeInjector(GuiceRunnable.java:62) ~[druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.CliInternalHadoopIndexer.run(CliInternalHadoopIndexer.java:110) ~[druid-services-0.12.3.jar:0.12.3]
>         at io.druid.cli.Main.main(Main.java:116) ~[druid-services-0.12.3.jar:0.12.3]
>         ... 6 more
> 

Command to run indexing :

`./cli.sh index hadoop hadoopDependencies org.apache.hadoop:hadoop-client:2.6.4 --no-default-hadoop mv-parquet-hadoop.json`

`hadoop-client:2.6.4` I downloaded through `pull-deps` - that's the closest version to CDH 5.14 that we use.

### PR DESCRIPTION
**Pull request by Tagar**
Better error reporting for https://github.com/apache/incubator-druid/issues/6673
- add explicit check that `metadataUpdateSpec` is mandatory

> Caused by: java.lang.NullPointerException
> at io.druid.cli.CliInternalHadoopIndexer$1.configure(CliInternalHadoopIndexer.java:97) ~[druid-services-0.12.3.jar:0.12.3]
> at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340) ~[guice-4.1.0.jar:?]
> at com.google.inject.spi.Elements.getElements(Elements.java:110) ~[guice-4.1.0.jar:?]
> at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:198) ~[guice-4.1.0.jar:?]

### CODE REVIEW

**Comment by jihoonson** [comment]
Hi @Tagar, thank you for your contribution! 

The CI fail looks legit. If you scroll up a bit, you can find maven test failure. They failed because of NPE at `metadataUpdateSpec`.

This is because `metadataUpdateSpec` is mandatory for only Cli Hadoop indexer and should be null for hadoop index task. Please check http://druid.io/docs/latest/ingestion/hadoop.html#ioconfig.

**Comment by Tagar** [comment]
Got it. Thanks @jihoonson 

So this check isn't possible as verify() at 
https://github.com/apache/incubator-druid/blob/d5633dd396a5cd16f98cb0e65d24ff5f8d6b33c3/indexing-hadoop/src/main/java/org/apache/druid/indexer/HadoopDruidIndexerConfig.java#L580

doesn't have a way of knowing if this spec is for `Cli Hadoop indexer` or for `hadoop index task` ?

That NPE error I described at https://github.com/apache/incubator-druid/issues/6673 is very cryptic and only way to know that `metadataUpdateSpec` was missing is to look at the source code.

**Comment by jihoonson** [comment]
Hmm, how about checking in `CliInternalHadoopIndexer.getHadoopDruidIndexerConfig()`?

**Comment by Tagar** [comment]
@jihoonson I will have a look into this.

Thanks.

**Comment by jihoonson** [comment]
Hi @Tagar, just want to check how this is going. If you have any further questions, please feel free ask me.

**Comment by Tagar** [comment]
@jihoonson thanks for the reminder. 
I wouldn't have time soon to have a look at this one. 
If somebody else takes over, it's okay with me.
Or I will have a look at this later. 
Thanks!

**Comment by jihoonson** [comment]
Thanks @Tagar. I'm closing this PR, but please reopen if you have time to work on it more.

**Pull request closed without merging**
