### PR TITLE
Support projection post operator

### PR DESCRIPTION
**Pull request by navis**
To retain only required columns in result. We can make columns via post-aggregator, etc. but cannot remove column which is not needed or should not be returned.

### CODE REVIEW

**Comment by navis** [comment]
example: 
```
"context": {
   "postProcessing" : {
      "type": "projection",
      "columns": ["column", "list", "you", "want", "to", "retain"]
   }
}
```

**Comment by gianm** [comment]
My feeling is that this is a neat feature but would better belong in the ToolChests (probably in `postMergeQueryDecoration`) than in a post processing operator. That way it would be extensible for custom queries.

**Comment by navis** [comment]
@gianm Thought about that but for that we need add new fields (something like "retainSolumns") in query objects. would it be better?

**Comment by gianm** [comment]
IMO it wouldn't be too bad to add an optional "projection" field to any query that wants to support projections. welcome opinions from others though.

**Comment by navis** [comment]
@gianm addressed comment. added `outputColumns` to timeseries/groupby/topn/select queries.

**Pull request closed without merging**
