### PR TITLE
Improper getter value is fixed.

### PR DESCRIPTION
**Pull request by kamaci**

### CODE REVIEW

**Comment by kamaci** [comment]
Do you mean adding a method to ApproximateHistogramPostAggregatorTest which extends BucketsPostAggregator?

**Comment by leventov** [comment]
Didn't you find this bug using some sort of inspection or static analysis?

**Comment by gianm** [comment]
> Do you mean adding a method to ApproximateHistogramPostAggregatorTest which extends BucketsPostAggregator?

I'd suggest adding a BucketsPostAggregatorTest that has a `testSerde()` method similar to ConstantPostAggregatorTest.

**Comment by kamaci** [comment]
@gianm  We can merge this PR if it is OK and I can create another PR which includes all tests for BucketsPostAggregatorTest?

**Comment by jihoonson** [comment]
I think the serde unit test should be included here because it fixes a bug.

**Comment by gianm** [comment]
I agree with @jihoonson, it is best to add a unit test in the same patch that fixes a bug.

**Comment by kamaci** [comment]
👍

**Comment by kamaci** [comment]
> > Do you mean adding a method to ApproximateHistogramPostAggregatorTest which extends BucketsPostAggregator?
> 
> I'd suggest adding a BucketsPostAggregatorTest that has a `testSerde()` method similar to ConstantPostAggregatorTest.

I've updated my PR.

**Comment by kamaci** [comment]
CI checks are OK 👍

**Pull request merged**
