### PR TITLE
Update license headers.

### PR DESCRIPTION
**Pull request by gianm**
For compliance with http://www.apache.org/legal/src-headers.html.

Part of #5835.

### CODE REVIEW

**Comment by gianm** [comment]
Most of this diff is updating one set of boilerplate headers to another. Other than that, there are a few files in the extendset package that I want to call attention to.

Files with a non-standard header (by Druid standards):

- https://github.com/apache/incubator-druid/blob/master/extendedset/src/main/java/io/druid/extendedset/intset/AbstractIntSet.java
- https://github.com/apache/incubator-druid/blob/master/extendedset/src/main/java/io/druid/extendedset/intset/ConciseSet.java
- https://github.com/apache/incubator-druid/blob/master/extendedset/src/main/java/io/druid/extendedset/intset/IntSet.java

The license on the these three files seems ok (it's Apache 2.0) and also we already call this copying out in the NOTICE file. So they seem ok to me but I'm just calling them out to double-check.

We also have two files with no license header:

- https://github.com/apache/incubator-druid/blob/master/extendedset/src/main/java/io/druid/extendedset/intset/ConciseSetUtils.java
- https://github.com/apache/incubator-druid/blob/master/extendedset/src/main/java/io/druid/extendedset/utilities/IntList.java

I am not sure what the provenance of these files is. @fjy - you did the initial checkin - do you remember if you wrote these files or if they were copied from somewhere else?

**Comment by gianm** [comment]
This is the earliest commit I can find for both of those files with no license headers. They both came from another repo that was copied into this one as part of #3694.

https://github.com/metamx/extendedset/commit/02366f18385b3e082866e5bbbd38357ceee13d79#diff-97bd266eb5d2e8b0e7a38a658921356d

**Comment by fjy** [comment]
ConciseSetUtils is from the original ConciseSet library under the Apache license. The license header is missing for the file but it should be the same as the rest of the files under the ConciseSet library (Apache v2).

**Comment by gianm** [comment]
@fjy Do you know if IntList is from the same place?

**Comment by fjy** [comment]
@gianm Yes IntList is from the same place

**Comment by himanshug** [comment]
:+1: 

ps: I don't see the merge button, need to get the permissions set up.

**Comment by gianm** [comment]
Thanks for reviewing, everyone -- I will merge this.

**Comment by asdf2014** [comment]
Hi, @gianm . Maybe we should update the wikipedia page of Druid too..

image

**Comment by gianm** [comment]
@asdf2014 Sounds great, go ahead and edit it! Anyone can edit Wikipedia 😄

**Pull request merged**
