### PR TITLE
 Fix - correcting conversion issue on sequence start number when doing…

### PR DESCRIPTION
**Pull request by acdn-mpreston**
… internal reset.

This is very similar to the issue described here: https://github.com/apache/incubator-druid/pull/7332

This only happens when the middle manager is cut off in the middle of an indexing task at a certain time which causes a race condition breaking the metadata type being stored for the datastore. It results in this exception:

"log":"2019-05-29T18:11:59,574 ERROR [KafkaSupervisor-npav-ts-metrics-1h] org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor - SeekableStreamSupervisor[npav-ts-metrics-1h] failed to handle notice: {class=org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor, exceptionType=class org.apache.druid.java.util.common.IAE, exceptionMessage=Expected instance of org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers, got org.apache.druid.indexing.seekablestream.SeekableStreamStartSequenceNumbers, noticeClass=RunNotice}\n","stream":"stdout","time":"2019-05-29T18:11:59.575001166Z"}
{"log":"org.apache.druid.java.util.common.IAE: Expected instance of org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers, got org.apache.druid.indexing.seekablestream.SeekableStreamStartSequenceNumbers\n","stream":"stdout","time":"2019-05-29T18:11:59.575037574Z"}
{"log":"\u0009at org.apache.druid.indexing.seekablestream.SeekableStreamEndSequenceNumbers.minus(SeekableStreamEndSequenceNumbers.java:159) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]\n","stream":"stdout","time":"2019-05-29T18:11:59.575080172Z"}
{"log":"\u0009at org.apache.druid.indexing.seekablestream.SeekableStreamDataSourceMetadata.minus(SeekableStreamDataSourceMetadata.java:95) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]\n","stream":"stdout","time":"2019-05-29T18:11:59.575086469Z"}
{"log":"\u0009at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.resetInternal(SeekableStreamSupervisor.java:1147) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]\n","stream":"stdout","time":"2019-05-29T18:11:59.575091749Z"}
{"log":"\u0009at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.getOffsetFromStorageForPartition(SeekableStreamSupervisor.java:2380) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]\n","stream":"stdout","time":"2019-05-29T18:11:59.575096907Z"}
{"log":"\u0009at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.generateStartingSequencesForPartitionGroup(SeekableStreamSupervisor.java:2357) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]\n","stream":"stdout","time":"2019-05-29T18:11:59.575102327Z"}
{"log":"\u0009at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.createNewTasks(SeekableStreamSupervisor.java:2254) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]\n","stream":"stdout","time":"2019-05-29T18:11:59.575107513Z"}
{"log":"\u0009at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.runInternal(SeekableStreamSupervisor.java:1013) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]\n","stream":"stdout","time":"2019-05-29T18:11:59.575113493Z"}
{"log":"\u0009at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor$RunNotice.handle(SeekableStreamSupervisor.java:265) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]\n","stream":"stdout","time":"2019-05-29T18:11:59.57511851Z"}
{"log":"\u0009at org.apache.druid.indexing.seekablestream.supervisor.SeekableStreamSupervisor.lambda$tryInit$3(SeekableStreamSupervisor.java:724) ~[druid-indexing-service-0.14.0-incubating.jar:0.14.0-incubating]\n","stream":"stdout","time":"2019-05-29T18:11:59.575123307Z"}
{"log":"\u0009at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66-internal]\n","stream":"stdout","time":"2019-05-29T18:11:59.575127713Z"}
{"log":"\u0009at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66-internal]\n","stream":"stdout","time":"2019-05-29T18:11:59.575187003Z"}
{"log":"\u0009at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_66-internal]\n","stream":"stdout","time":"2019-05-29T18:11:59.575193321Z"}
{"log":"\u0009at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_66-internal]\n","stream":"stdout","time":"2019-05-29T18:11:59.575197266Z"}
{"log":"\u0009at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66-internal]\n","stream":"stdout","time":"2019-05-29T18:11:59.575201222Z"}

### CODE REVIEW

**Comment by gianm** [comment]
@acdn-mpreston, could you please raise this patch against `master` instead of `0.14.0-incubating`?

**Comment by acdn-mpreston** [comment]
Resubmitted on the master and 0.14.0-incubating branches properly. We are currently using the 0.14.0-incubating branch and would love to have it included there.

**Comment by Stephan3555** [comment]
We are running currently in the same issue. Is there a quickfix to solve this right now?

**Comment by acdn-mpreston** [comment]
@Stephan3555 I have not been able to get a working fix yet. Every solution I create results in datasource metadata that is the "wrong" type later in the indexing process after the reset. The frustrating thing is the end and start sequence numbers are really the same and the addition of the conversion method from end sequence number to start sequence number looks to be a solution added to patch something quickly. I will post again if I figure something out.

**Comment by acdn-mpreston** [comment]
Also @Stephan3555 you may want to follow https://github.com/apache/incubator-druid/pull/7831 as this is the commit against master that I had previously submitted, but then I ran into further issues with the fix. I am still trying to sort out a better fix, but it is a difficult problem to reproduce and each "fix" I put in exposes another break down the line in how the sequence number metadata is handled. There are a lot of assumptions about if the metadata will have start or end sequence number format at different parts on which I get hung up.

**Comment by Stephan3555** [comment]
Thanks for the update and thanks for the effort @acdn-mpreston!

**Comment by acdn-mpreston** [comment]
@Stephan3555 I have had no luck creating a PR to fix this issue, but I have created a custom build workaround that does seem to be working for the Kafka ingestion workflow. I have created issue https://github.com/apache/incubator-druid/issues/7926 which includes a 'Current Workaround' section that documents what I have done to create my custom build. The basic idea is to get rid of having 2 classes for sequence number offset management and instead just have one class which will mean there will never be a situation where you get mismatched class types in the datasource metadata.

After installing my new build, the bad datasource metadata was corrected and all my indexing tasks started working and have been working ever since. I am currently trying to reproduce the failure case that is documented in this PR before I consider using this custom image in production. 

Let me know if you have any questions.

**Pull request closed without merging**
