### PR TITLE
set DRUID_AUTHORIZATION_CHECKED attribute for router endpoints

### LINKED ISSUE #6786: apache-druid-0.13.0-incubating router /druid/router/v1/brokers
ERROR PreResponseAuthorizationCheckFilter:106 - Request did not have an authorization check performed.: {class=org.apache.druid.server.security.PreResponseAuthorizationCheckFilter, uri=/druid/router/v1/brokers, method=GET, remoteAddr=172.19.104.129, remoteHost=172.19.104.129}

### PR DESCRIPTION
**Pull request by pjain1**
Fixes #6786 

### Description

Router does not perform any authorization checks and depends on requests forwarded to other nodes to perform authorization and set `DRUID_AUTHORIZATION_CHECKED` header. It works fine in most cases, however for requests that are not forwarded to other nodes and are not in unsecured path list, this header is not set, thus `PreResponseAuthorizationCheckFilter` throws exception. Example of this would be `/druid/router/v1/brokers` end point on router.

To fix this added appropriate resource filter to router endpoint.

### CODE REVIEW

**Comment by gianm** [comment]
I would think the `druid/router/v1/brokers` endpoint should at least require STATE READ permissions?

**Comment by pjain1** [comment]
Changed the code and PR description as per your recommendation. Thanks

**Comment by egor-ryashin** [comment]
@pjain1 I wonder if that can be unit-tested easily?

**Comment by pjain1** [comment]
@egor-ryashin  added `RouterResource` to ResourceFilter test framework

**Pull request merged**
