### PR TITLE
Modify batch index task naming to accomodate simultaneous tasks 

### LINKED ISSUE #8494: Fix batch index task naming convention to accommodate simultaneous tasks
### Description
Modify the batch indexing task ID generation logic from

 `<index_type_name>_<datasource>_timestamp` to 
`<index_type_name>_<datasource>_<random_id>`
This would impact native index tasks as well as hadoop index tasks.

### Motivation
With the existing task naming convention, if there are multiple indexing tasks submitted at the same time for a datasource, only one of the tasks gets accepted and the remaining tasks fail with  `Task[xxx] already exists`. I'd like to modify the naming convention to the one mentioned above, so that this issue can be avoided.
@jihoonson Any comments regarding this?

### PR DESCRIPTION
**Pull request by a2l007**
Fixes #8494  .

### Description
Modifies the index task name generation logic to as follows:
Before: `index_hadoop_datasource_2019-09-27T21:11:29.162Z`
After: `index_hadoop_datasource_wjkrtyiz_2019-09-27T21:11:29.162Z`

<hr>

This PR has:
- [x] been self-reviewed.
- [x] been tested in a test Druid cluster.

<hr>

### CODE REVIEW

**Comment by jihoonson** [comment]
@a2l007 thank you for raising this PR! Have you had a chance to check @gianm's comment?

**Comment by a2l007** [comment]
Sorry for the delay.
@gianm Thanks, that makes sense to me. I'm made the corresponding changes.

**Comment by jihoonson** [comment]
Sorry for the delay. I will review this PR in a couple of days.

**Comment by a2l007** [comment]
@jihoonson Thanks for reviewing. Apart from the random string, the timestamp is also part of the task name. Wouldn't that be sufficient to avoid task name collisions?

**Pull request merged**
