### PR TITLE
IndexedIntsWriter need not to accept generic Object

### PR DESCRIPTION
**Pull request by navis**
Currently, IndexedIntsWriter accepts generic Object type and IndexMerger delivers int[] after converting it to List<Integer>. It looks definitely unnecessary.

### CODE REVIEW

**Comment by fjy** [comment]
@navis does this have any perf change?

**Comment by navis** [comment]
It's more about memory not performance but I'll try.

**Comment by navis** [comment]
Adding 100M int[2] into tmpFile took 12749 msec with this and 15110 msec in trunk. But I don't think this means any performance boost by this.

**Comment by fjy** [comment]
@navis changes to core files require extremely careful review and testing, which is difficult for us to do without more feedback. Is this a PR a critical change? Are there critical performance bottlenecks that are being fixed?

**Pull request closed without merging**
