### PR TITLE
combine druid-api, druid-common, java-util into druid-core

### PR DESCRIPTION
**Pull request by clintropolis**
Steps towards #4312, retrying what #5490 was attempting.

This PR is strictly moving files into a `druid-core` library/folder structure and fixing up `pom.xml` files to change all references of `druid-api`, `druid-common`, and `java-util` to `druid-core`. I have not combined `druid-processing` to try to limit the extent of interference with existing PRs. 

Additionally, I have not refactored file package placement or any of the other cleanup this move allows, which I think can be done in a follow up PR, to minimize reviewer mental cost.

Passing unit and integration tests for me and everything appears to be functioning, but I did have to add a log4j xml file to integration tests project, I have no idea what sort of magic was being done before, but I suspected it was related to the problems ran into #5490 too. Let's see if this one has any better luck with travis.

### CODE REVIEW

**Comment by jihoonson** [comment]
+1 after CI

**Comment by b-slim** [comment]
@clintropolis can you please solve conflicts +1

**Comment by drcrallen** [comment]
For things like this, can we get a warning in the dev list? this is hugely impacting some outstanding PRs

**Comment by clintropolis** [comment]
Sorry about that, this got merged way quicker than I imagined it would, hopefully it's not too painful :(

Since it's mostly just moving files and pom fixup, having [similar settings in place](https://github.com/apache/incubator-druid/pull/6266#issuecomment-417172303) as were needed during the `io.druid.*` rename to `org.apache.druid.*` should make it so things aren't too bad in most cases I hope.

**Pull request merged**
