### PR TITLE
[Backport] HRTR: make pending task execution handling to go through all tasks on not finding worker slots (#8697)

### PR DESCRIPTION
**Pull request by himanshug**
backports #8697

### CODE REVIEW

**Comment by jihoonson** [comment]
Updated the title to help the missing backports script.

**Comment by himanshug** [comment]
@jihoonson thanks, didn't know about that .. it would be great if that can be documented in `CONTRIBUTING.md` .

**Comment by jihoonson** [comment]
Sounds great. It would also be great if we have a script for backporting PRs. I could be able to work on these sometime.. probably.

**Comment by himanshug** [comment]
oh, from your message I got the [wrong] idea that there was probably some script that was doing something with backported PRs and that is why titles had to follow a specific format .

**Comment by jihoonson** [comment]
Aha sorry for the confusion. You got the right idea. `distribution/bin/find-missing-backports.py` searches for all PRs which are in master but not in the given milestone branch. This works based on some pattern matching on the PR title.

> Sounds great. It would also be great if we have a script for backporting PRs. I could be able to work on these sometime.. probably.

My comment was about a script backporting one PR in master into a branch. [Gian shared his script before](http://mail-archives.apache.org/mod_mbox/druid-dev/201805.mbox/browser) which is not completely configurable (for example, you have to fix the hard-corded user name in the script) and probably we can further generalize it.

**Comment by himanshug** [comment]
got it, thanks

**Pull request merged**
