### PR TITLE
fix issue #7607

### PR DESCRIPTION
**Pull request by AlexanderSaydakov**

### CODE REVIEW

**Comment by jihoonson** [comment]
Should we add a unit test?

**Comment by AlexanderSaydakov** [comment]
There is no change in Druid code. And we added a test in the sketches-core code.

**Comment by AlexanderSaydakov** [comment]
I guess the artifacts did not propagate yet. I see them here:
https://repo1.maven.org/maven2/com/yahoo/datasketches/sketches-core/0.13.3/

**Comment by jihoonson** [comment]
Ok. Will restart CI after a few mins.

**Comment by clintropolis** [comment]
Hmm, the failure is perhaps no longer related to missing artifacts:
```
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.BannedDependencies failed with message:
Found Banned Dependency: com.google.code.findbugs:annotations:jar:3.0.0
Use 'mvn dependency:tree' to locate the source of the banned dependencies.
```
at https://travis-ci.org/apache/incubator-druid/jobs/530049926#L3162

Doing a quick search, this library is licensed as `lgpl` which is perhaps the reason for this issue? Is this a new dependency between 0.13.1 and 0.13.3? I wonder if it can be safely excluded from the datasketches extension pom?
```
               <exclusions>
                    <exclusion>
                        <groupId>com.google.code.findbugs</groupId>
                        <artifactId>annotations</artifactId>
                    </exclusion>
                </exclusions>
```

**Pull request merged**
