### PR TITLE
Implementing dropwizard emitter for druid (fixes #3927)

### LINKED ISSUE #3927: Dropwizard metric emitter for druid metrics
A new metric emitter which would convert the druid metrics into corresponding dropwizard metrics(http://metrics.dropwizard.io/3.1.0/)  and then use various emitters of dropwizard like statsd,http,console,jmx etc to emit the metrics to various sinks.
Dropwizard is widely used metric collection library and already has emitters to lot of metric stores.

### PR DESCRIPTION
**Pull request by rohitkochar**
Corresponding issues are 
https://github.com/druid-io/druid/issues/3927
https://github.com/druid-io/druid/issues/1996

### CODE REVIEW

**Comment by rohitkochar** [comment]
@b-slim @himanshug 
Requesting you to review this pull request.
The code structure is based on the graphite-emitter contributed by @b-slim

**Comment by jeffwidman** [comment]
Any update on this?

**Comment by dkhwangbo** [comment]
Hi. Any update? Any schedule to review it?

**Comment by dkhwangbo** [comment]
Hi. Any update? Any schedule to review it?

**Comment by dkhwangbo** [comment]
Hi. Any update? Any schedule to review it?

**Comment by jihoonson** [comment]
Sorry about the delayed review. @rohitkochar would you please update this PR by merging master? You also need to update the package name and the license of all new files to `org.apache.druid` and the Apache license, respectively.

**Comment by mlubavin-vg** [comment]
This would be great if it would allow emitting metrics in the various dropwizard supported formats.  We're specifically looking for prometheus exporting, which can be hooked up through the jmx exporter with https://github.com/prometheus/jmx_exporter

**Comment by nishantmonu51** [comment]
@rohitkochar Thanks for the PR. We are also looking for enabling exposing druid metrics via JMX. 
@rohitkochar, are you still planning to work on this PR ?

**Comment by nishantmonu51** [comment]
FYI, I am working on refactoring this patch for latest druid. Will start by cherry-picking @rohitkochar commit so that he gets credit for the work done.

**Comment by nishantmonu51** [comment]
Closing in favor of https://github.com/apache/incubator-druid/pull/7363

**Pull request closed without merging**
