### PR TITLE
fix druid-basic-security rolling upgrade bug

### PR DESCRIPTION
**Pull request by hellobabygogo**

### CODE REVIEW

**Comment by jon-wei** [comment]
-1, this change is not needed, did you remember to set the "type" property for allowAll?

e.g. 

```
druid.auth.authenticatorChain=["allowAll", "basic"]
...
druid.auth.authenticator.allowAll.type=allowAll
```

**Comment by hellobabygogo** [comment]
> -1, this change is not needed, did you remember to set the "type" property for allowAll?
> 
> e.g.
> 
> ```
> druid.auth.authenticatorChain=["allowAll", "basic"]
> ...
> druid.auth.authenticator.allowAll.type=allowAll
> ```

hi jon-wei
I tryed to add druid.auth.authenticator.allowAll.type=allowAll, but there is a error when i start coordinator node !
image

**Comment by hellobabygogo** [comment]
> -1, this change is not needed, did you remember to set the "type" property for allowAll?
> 
> e.g.
> 
> ```
> druid.auth.authenticatorChain=["allowAll", "basic"]
> ...
> druid.auth.authenticator.allowAll.type=allowAll
> ```

thank you very much !

**Comment by jon-wei** [comment]
@hellobabygogo cool, glad you got it working!

**Pull request closed without merging**
