### PR TITLE
Update init

### PR DESCRIPTION
**Pull request by michael-trelinski**
Fix bin/init to source from proper directory.

### CODE REVIEW

**Comment by fjy** [comment]
@jon-wei can you take a quick look?

**Comment by QiuMM** [comment]
LGTM, but I think use such relative path is not a good way since it depends on where you run this file i.e. `run bin/init` would work but `run ./init` would not. Use `dirname $0` to get parent directory of this bash file and tweak the path.

**Comment by jihoonson** [comment]
LGTM. @QiuMM's suggestion also sounds good to me though.

**Comment by jon-wei** [comment]
Hm, this script is not used anymore since we replaced the old quickstart with the new tutorials, I'll do a patch shortly for some cleanup around that area

**Pull request merged**
