### PR TITLE
Support double type metric

### PR DESCRIPTION
**Pull request by navis**
We suffered some precision problems of metrics because currently it's allowed to be one of float or long type. This patch is for supporting double type metric in druid. I'm expecting BigDecimal type could be considered for next target.

### CODE REVIEW

**Comment by gianm** [comment]
@navis, this looks really useful! Haven't read everything yet, but initial comments:

- why not always use a DoubleColumnSelector for the DoubleSumAggregator? It's going to need to get cast into a double and added into a double anyway.
- looks at indexing time, `inputType` of the generic aggregator factories determines the type of the column stored on disk. this is a bit counter-intuitive! maybe something neutral like `valueType` would be more intuitive.
- are you expecting we would deprecate `{double,long}{min,max,sum}` aggregator factories in favor of the "generic" versions?
- are you using this in production?

**Comment by navis** [comment]
@gianm 

- it's generally acceptable to use just double selector as input especially when the columns is already a numeric value in input row but when it's string and should be parsed into, `Long.valueOf` is way lighter than `Double.valueOf` (10x on cpu time) and also possible to loose some precisions. 
- `inputType` is from type of column selector at first. I'm ok whatever the name would be.
- I didn't think about that. should we keep it for compatibility?
- we are using `DoubleColumnSelector` modified to accept double input and store it as double.  I regret that because it will be a problem someday.

**Comment by b-slim** [comment]
@navis and @fjy  are you guys still working on this ?
We also have some issue with precision lose and would like to see this Done. I can help reviewing or taking from you guys have stopped. 
Please let me know ASAP thanks.

**Comment by Dylan1312** [comment]
Closing as I believe this was covered in #4491

**Pull request closed without merging**
