### PR TITLE
Fix statsd types

### PR DESCRIPTION
**Pull request by xvrl**
cc @michaelschiff @dene14

### CODE REVIEW

**Comment by michaelschiff** [comment]
LGTM

Can we update the documentation to make the intent clearer for `jvm/gc/cpu`?

jvm/gc/cpu | Cpu time in Nanoseconds spent on garbage collection. | gcName, gcGen | Sum of jvm/gc/cpu should be within 10-30% of sum of jvm/cpu/total, depending on the GC algorithm used (reported by JvmCpuMonitor)
-- | -- | -- | --

"Cpu time in Nanoseconds" sounds like a Timer to me.  Maybe something like "Count of Cpu time in Nanoseconds spent on garbage collection"

**Comment by clintropolis** [comment]
travis seems messed up on this:
```
The command "eval git clone --depth=50 --branch=fix-dogstatsd-types https://github.com/apache/incubator-druid.git apache/incubator-druid " failed. Retrying, 2 of 3.
Cloning into 'apache/incubator-druid'...
warning: Could not find remote branch fix-dogstatsd-types to clone.
fatal: Remote branch fix-dogstatsd-types not found in upstream origin
```

**Comment by xvrl** [comment]
@clintropolis I confused travis because I accidentally create the branch in the Apache repo instead of my fork

**Comment by xvrl** [comment]
@michaelschiff sure I can update the docs to clarify.

**Pull request merged**
