### PR TITLE
Web console: celebrate array based groupBy by supporting resultAsArray in the console

### PR DESCRIPTION
**Pull request by vogievetsky**
[Array based groupBys](https://github.com/apache/incubator-druid/pull/8196) are really cool. Also fast. People will want to play with them. Where will the people go? The console of course. And when people go to the console to set `"resultAsArray": true` on their queries the console will know how to render that response.

This PR has:
- [x] been self-reviewed.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by fjy** [comment]
@vogievetsky do we need an explicit field? I think that's too much overhead. The console should be able to auto render.

**Comment by vogievetsky** [comment]
@fjy the console auto renders based on your query as it does with all of them. If you set `resultAsArray: true` in the query context of a grouBy (this is a new option) the query response will have array rows. With this PR the console will be able to auto render it. Before this PR it would give you an error in the table.

**Comment by vogievetsky** [comment]
actually you are right, it should 100% auto detect everything from the query shape

**Comment by vogievetsky** [comment]
Ok updated to address @fjy 's comments. Also updated the licenses that went out of date after the segment timeline PR was merged in.

**Pull request merged**
