### PR TITLE
 Minor change in the "Start up Druid services" Section

### PR DESCRIPTION
**Pull request by hpandeycodeit**
In the current "Start up Druid services" section, when starting the services in order ( as mentioned), we get this error shen starting the 1st two services. : 
 
```
io.druid.java.util.common.IOE: No known server
	at io.druid.discovery.DruidLeaderClient.getCurrentKnownLeader(DruidLeaderClient.java:276) ~[druid-server-0.12.1.jar:0.12.1]
	at io.druid.discovery.DruidLeaderClient.makeRequest(DruidLeaderClient.java:128) ~[druid-server-0.12.1.jar:0.12.1]
	at io.druid.query.lookup.LookupReferencesManager.fetchLookupsForTier(LookupReferencesManager.java:569) ~[druid-server-0.12.1.jar:0.12.1]
	at io.druid.query.lookup.LookupReferencesManager.tryGetLookupListFromCoordinator(LookupReferencesManager.java:420) ~[druid-server-0.12.1.jar:0.12.1]
	at io.druid.query.lookup.LookupReferencesManager.lambda$getLookupListFromCoordinator$4(LookupReferencesManager.java:398) ~[druid-server-0.12.1.jar:0.12.1]
	at io.druid.java.util.common.RetryUtils.retry(RetryUtils.java:63) [java-util-0.12.1.jar:0.12.1]
	at io.druid.java.util.common.RetryUtils.retry(RetryUtils.java:81) [java-util-0.12.1.jar:0.12.1]
	at io.druid.query.lookup.LookupReferencesManager.getLookupListFromCoordinator(LookupReferencesManager.java:388) [druid-server-0.12.1.jar:0.12.1]

```
So changing the order and moving these two process to the end: 

```
java cat conf-quickstart/druid/historical/jvm.config | xargs -cp "conf-quickstart/druid/_common:conf-quickstart/druid/historical:lib/*" io.druid.cli.Main server historical
java cat conf-quickstart/druid/broker/jvm.config | xargs -cp "conf-quickstart/druid/_common:conf-quickstart/druid/broker:lib/*" io.druid.cli.Main server broker
```

### CODE REVIEW

**Comment by jihoonson** [comment]
Hi @hpandeycodeit, the exception should be fine. In Druid, each component should retry until it finds the current leader.

I think it's more important to replace those long java commands with our simple scripts. For example, we have a script, i.e., `bin/broker.sh` to start/stop brokers. So, we can replace `java cat conf-quickstart/druid/broker/jvm.config | xargs -cp "conf-quickstart/druid/_common:conf-quickstart/druid/broker:lib/*" io.druid.cli.Main server broker` to use this script. Probably we need to improve those scripts to accept an extra parameter for configuration directory. Similar for other components. Are you interested in this?

**Comment by hpandeycodeit** [comment]
@jihoonson, 
Yes, I am interested in this. Do we have scripts ready for all these java commands or for just one? 
And can you explain why an " extra parameter for configuration directory" is needed?

**Comment by hpandeycodeit** [comment]
@jihoonson ,
The scripts are there but doesn't look like it's working: 

For eg: 

$./broker.sh start
Started broker node (5282)
$./broker.sh status
STOPPED

**Comment by jihoonson** [comment]
It should work. Would you please check your broker logs?

**Comment by jon-wei** [comment]
> I think it's more important to replace those long java commands with our simple scripts. For example, we have a script, i.e., bin/broker.sh to start/stop brokers. So, we can replace java cat conf-quickstart/druid/broker/jvm.config | xargs -cp "conf-quickstart/druid/_common:conf-quickstart/druid/broker:lib/*" io.druid.cli.Main server broker to use this script. Probably we need to improve those scripts to accept an extra parameter for configuration directory. Similar for other components. Are you interested in this?

Just want to mention that I've been working on some improvements to the Druid quickstart with some new tutorials; as part of that upcoming patch, I'll be contributing a new "supervise" tool for running Druid services. The PR should be available in the next couple of days.

**Comment by jihoonson** [comment]
@jon-wei that sounds nice!

**Comment by jon-wei** [comment]
@hpandeycodeit For that error, you'd want to adjust `-XX:MaxDirectMemorySize=4096m` in the `jvm.config` file for the corresponding service

**Comment by asdf2014** [comment]
Hi, @hpandeycodeit . I also encountered this situation. There is [formula](http://druid.io/docs/latest/configuration/broker.html#processing) for it in the Druid doc. In my experience with this problem, you may need to add `-XX:MaxDirectMemorySize` option to both of those `conf/druid/historical/jvm.config` and `conf/druid/broker/jvm.config` files  :sweat_smile:

**Comment by hpandeycodeit** [comment]
Hi @asdf2014, 

Thanks, that helped with the memory issue but I am hitting this new issue when trying to start the services using any .sh file in the bin directory.

Caused by: java.net.UnknownHostException: zk.host.ip: unknown error
 
Zookeeper is running. Do I have to set this "zk.host.ip" somewhere?

**Pull request closed without merging**
