### PR TITLE
Optimize images by ImgBot

### PR DESCRIPTION
**Pull request by asdf2014**
ImgBot uses lossless compression on image files, reducing the size by 35%.

<br />
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /publications/radstack/figures/precompute.png | 54.20kb | 16.97kb | 68.69% |
| /web-console/favicon.png | 4.41kb | 1.61kb | 63.58% |
| /docs/img/indexing_service.png | 47.37kb | 21.96kb | 53.64% |
| /docs/img/segmentPropagation.png | 62.94kb | 29.85kb | 52.57% |
| /docs/content/tutorials/img/tutorial-quickstart-01.png | 55.62kb | 29.13kb | 47.62% |
| /docs/content/tutorials/img/tutorial-deletion-02.png | 791.43kb | 429.30kb | 45.76% |
| /docs/content/tutorials/img/tutorial-deletion-03.png | 786.79kb | 427.05kb | 45.72% |
| /docs/content/tutorials/img/tutorial-retention-00.png | 135.06kb | 75.88kb | 43.82% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-10.png | 77.23kb | 43.47kb | 43.71% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-01.png | 97.03kb | 55.16kb | 43.15% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-07.png | 79.49kb | 45.44kb | 42.84% |
| /docs/content/tutorials/img/tutorial-retention-02.png | 401.30kb | 234.68kb | 41.52% |
| /docs/content/tutorials/img/tutorial-compaction-06.png | 343.27kb | 201.87kb | 41.19% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-09.png | 105.14kb | 61.86kb | 41.16% |
| /docs/content/tutorials/img/tutorial-retention-06.png | 227.57kb | 134.35kb | 40.97% |
| /docs/content/tutorials/img/tutorial-compaction-04.png | 304.83kb | 180.04kb | 40.94% |
| /docs/content/tutorials/img/tutorial-compaction-02.png | 273.18kb | 162.67kb | 40.45% |
| /docs/content/tutorials/img/tutorial-query-05.png | 85.03kb | 50.64kb | 40.44% |
| /publications/radstack/figures/druid_vs_bigquery.png | 155.44kb | 92.85kb | 40.27% |
| /docs/content/tutorials/img/tutorial-kafka-02.png | 122.51kb | 73.93kb | 39.65% |
| /docs/content/tutorials/img/tutorial-deletion-01.png | 70.37kb | 42.56kb | 39.52% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-06.png | 103.50kb | 62.79kb | 39.33% |
| /docs/content/tutorials/img/tutorial-batch-submit-task-01.png | 111.25kb | 67.73kb | 39.12% |
| /docs/content/tutorials/img/tutorial-query-03.png | 103.60kb | 63.51kb | 38.69% |
| /docs/content/tutorials/img/tutorial-query-04.png | 105.79kb | 64.87kb | 38.69% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-11.png | 130.20kb | 81.34kb | 37.53% |
| /docs/content/tutorials/img/tutorial-query-07.png | 122.52kb | 76.79kb | 37.32% |
| /docs/content/tutorials/img/tutorial-kafka-01.png | 133.12kb | 83.47kb | 37.30% |
| /docs/content/tutorials/img/tutorial-query-06.png | 127.55kb | 80.28kb | 37.06% |
| /docs/content/tutorials/img/tutorial-batch-submit-task-02.png | 133.07kb | 84.06kb | 36.83% |
| /docs/content/tutorials/img/tutorial-retention-05.png | 60.19kb | 38.08kb | 36.74% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-03.png | 211.92kb | 134.22kb | 36.66% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-05.png | 250.36kb | 158.68kb | 36.62% |
| /publications/radstack/figures/radstack.png | 16.80kb | 10.67kb | 36.48% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-08.png | 158.59kb | 101.49kb | 36.00% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-04.png | 255.10kb | 163.33kb | 35.97% |
| /docs/content/tutorials/img/tutorial-query-02.png | 126.92kb | 81.42kb | 35.85% |
| /docs/content/tutorials/img/tutorial-compaction-01.png | 53.86kb | 34.87kb | 35.25% |
| /docs/img/druid-architecture.png | 202.23kb | 130.97kb | 35.24% |
| /docs/content/tutorials/img/tutorial-retention-01.png | 52.69kb | 34.35kb | 34.81% |
| /docs/img/druid-timeline.png | 35.87kb | 23.59kb | 34.22% |
| /docs/content/tutorials/img/tutorial-query-01.png | 149.53kb | 98.56kb | 34.08% |
| /docs/content/tutorials/img/tutorial-retention-04.png | 65.91kb | 43.57kb | 33.89% |
| /docs/content/tutorials/img/tutorial-compaction-08.png | 42.24kb | 28.08kb | 33.53% |
| /docs/content/tutorials/img/tutorial-compaction-07.png | 39.17kb | 26.06kb | 33.47% |
| /docs/content/tutorials/img/tutorial-compaction-03.png | 39.17kb | 26.13kb | 33.30% |
| /docs/content/tutorials/img/tutorial-compaction-05.png | 38.85kb | 25.96kb | 33.17% |
| /publications/demo/figures/throughput_vs_cardinality.png | 73.49kb | 49.31kb | 32.90% |
| /publications/radstack/figures/throughput_vs_cardinality.png | 73.49kb | 49.31kb | 32.90% |
| /publications/whitepaper/figures/throughput_vs_cardinality.png | 73.49kb | 49.31kb | 32.90% |
| /docs/content/tutorials/img/tutorial-retention-03.png | 43.11kb | 29.33kb | 31.97% |
| /publications/radstack/figures/throughput_vs_num_dims.png | 72.86kb | 49.72kb | 31.76% |
| /publications/whitepaper/figures/throughput_vs_num_dims.png | 72.86kb | 49.72kb | 31.76% |
| /publications/demo/figures/throughput_vs_num_dims.png | 72.86kb | 49.72kb | 31.76% |
| /publications/radstack/figures/joined.png | 164.14kb | 113.47kb | 30.87% |
| /docs/content/tutorials/img/tutorial-batch-data-loader-02.png | 508.93kb | 351.85kb | 30.87% |
| /publications/radstack/figures/imps_clicks.png | 190.95kb | 132.70kb | 30.51% |
| /publications/radstack/figures/shuffled.png | 180.46kb | 128.21kb | 28.95% |
| /publications/radstack/figures/pipeline.png | 392.54kb | 281.93kb | 28.18% |
| /docs/img/druid-manage-1.png | 108.94kb | 78.53kb | 27.92% |
| /publications/radstack/figures/throughput_vs_num_metrics.png | 85.25kb | 61.80kb | 27.51% |
| /publications/demo/figures/throughput_vs_num_metrics.png | 85.25kb | 61.80kb | 27.51% |
| /publications/whitepaper/figures/throughput_vs_num_metrics.png | 85.25kb | 61.80kb | 27.51% |
| /docs/img/druid-production.png | 50.00kb | 39.18kb | 21.63% |
| /docs/img/druid-dataflow-3.png | 88.25kb | 69.75kb | 20.96% |
| /publications/demo/figures/realtime_flow.png | 51.12kb | 40.61kb | 20.56% |
| /publications/demo/figures/realtime_timeline.png | 36.15kb | 29.24kb | 19.12% |
| /publications/demo/figures/tpch_scaling.png | 43.21kb | 34.97kb | 19.08% |
| /publications/demo/figures/caching.png | 35.26kb | 29.09kb | 17.49% |
| /dev/intellij-sdk-config.jpg | 1,019.35kb | 864.37kb | 15.20% |
| /docs/img/druid-column-types.png | 101.53kb | 91.17kb | 10.20% |
| /docs/img/druid-dataflow-2x.png | 138.30kb | 127.11kb | 8.09% |
| | | | |
| **Total :** | **10,997.25kb** | **7,160.16kb** | **34.89%** |

### CODE REVIEW

**Comment by vogievetsky** [comment]
How are is this tool getting run? I am adding a ton of images as part of https://github.com/apache/incubator-druid/pull/7863 and would like to compress them also (also there will probably be conflicts with this PR

**Comment by asdf2014** [comment]
Hi, @vogievetsky . I tried to install `ImgBot` in Apache Druid, but I don't have this permission. So, I have to create a PR to submit these optimizations. If necessary, then I will create another PR after the #7863 has been merged.

**Comment by vogievetsky** [comment]
You might want to rerun these now to optimize all the images that were added in https://github.com/apache/incubator-druid/pull/7863

**Comment by asdf2014** [comment]
@vogievetsky Sure, I will keep working on it.

**Comment by asdf2014** [comment]
@vogievetsky It's done. PTAL.

**Comment by asdf2014** [comment]
@vogievetsky Do you still have time to take a look at this PR?

**Comment by vogievetsky** [comment]
I think it looks great! Thank you for re-running

**Comment by vogievetsky** [comment]
👍

**Pull request merged**
