### PR TITLE
Fix filterSegments for TimeBoundary and DataSourceMetadata queries

### PR DESCRIPTION
**Pull request by jihoonson**
Fixes https://github.com/apache/incubator-druid/issues/6177.

### CODE REVIEW

**Comment by fjy** [comment]
@jihoonson can you look at test failures?

**Comment by jihoonson** [comment]
@fjy thanks. Fixed.

**Comment by jihoonson** [comment]
Added `Design Review` since it changes a PublicApi.

**Comment by fjy** [comment]
👍

**Pull request merged**
