### PR TITLE
Web-console: Add run keyboard short cut to sql-control

### PR DESCRIPTION
**Pull request by mcbrewster**
Screen Shot 2019-05-28 at 6 01 08 PM

Pressing control+enter will now have the same function as pressing run with limit. 

This is achieved by using the hotkeys decorator from the blue print library. The hotkey is set with a global attribute so if the short cut is used any time on the sql-view page the onRunClick function will be called.

### CODE REVIEW

**Comment by vogievetsky** [comment]
Looking good, I wonder if the snapshot tests need to be updated at all.

**Comment by mcbrewster** [comment]
> Looking good, I wonder if the snapshot tests need to be updated at all.

They do I just updated them

**Comment by vogievetsky** [comment]
Ok, that makes sense. Also could you please not force push as much. It is totally ok to just add a bunch of small commits. They will be squashed when the PR is merged.

**Comment by vogievetsky** [comment]
Huh, I can't actually get this to work on my computer

**Comment by mcbrewster** [comment]
> Huh, I can't actually get this to work on my computer
I think maybe it's because you couldn't use hot keys while typing, now you can. Does that fix it?

**Comment by vogievetsky** [comment]
YES! Awesome. 👍

**Comment by gianm** [comment]
> Ok, that makes sense. Also could you please not force push as much. It is totally ok to just add a bunch of small commits. They will be squashed when the PR is merged.

Btw, in general in Druid we recommend avoiding force pushes, since they confuse the GitHub UI that shows reviewers what changed since their last review. It extends to incorporating changes from mast too, where we suggest using `git merge master` rather than `git rebase master` in order to avoid force pushes.

**Pull request merged**
