### PR TITLE
Web console: LGTM alert squash + final fixes

### PR DESCRIPTION
**Pull request by vogievetsky**
This PR is the final fixes for the 0.16.0 release of the web console it addresses:

- remaining issues from parallel with forceGuaranteedRollup mode
- fixes issues identified by LGTM
- updates deps
- less dropdowns because dropdowns make people sad
- improves size of data loader tiles:

image

This PR has:
- [x] been self-reviewed.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by vogievetsky** [comment]
image
 
Booya

**Comment by leventov** [comment]
What has happened to the old console? Where it has been moved? Commit ["mv old console"](https://github.com/apache/incubator-druid/pull/8351/commits/034987b233596243a85b07f355c11d7f5a19f750) looks like it removes the old console

**Comment by vogievetsky** [comment]
@leventov that commit removed the old console and then I changed my mind and put it back in https://github.com/apache/incubator-druid/pull/8351/commits/cadb285e4c93783e72029bf0e1aa9e6c98a6adac the missing file it a mistake and I will fix ASAP.

**Comment by vogievetsky** [comment]
This is fixed in: https://github.com/apache/incubator-druid/pull/8387

**Pull request merged**
