### PR TITLE
Upgrade joda-time to 2.10.5

### PR DESCRIPTION
**Pull request by a2l007**
Upgrading joda time to include the latest timezone data.
An important timezone change is that Brazil recently scrapped Daylight savings (https://www.timeanddate.com/news/time/brazil-scraps-dst.html) and this version includes that change.

### CODE REVIEW

**Comment by jihoonson** [comment]
Seems like there was an issue with thrift repo. Restarted failed ones.

**Comment by jihoonson** [comment]
Would you please merge master so that LGTM and TC become happy?

**Comment by a2l007** [comment]
@jihoonson Everybody is happy now!

**Comment by jihoonson** [comment]
@a2l007 thanks!

**Pull request merged**
