### PR TITLE
Store select/groupby query result to filesystem

### PR DESCRIPTION
**Pull request by navis**
Some queries make a lot of rows. If result can be stored filesystem, we can negate network overhead.

### CODE REVIEW

**Comment by fjy** [comment]
@navis we've actually been thinking about how to solve this problem for a long time. I think @himanshug was looking into this problem as well. It'd be great if we can do on-disk merges for groupBy so that much larger result sets can be returned.

**Comment by navis** [comment]
@fjy This is just for forwarding final result as tabular format to file or something. Seemed different with what you are expecting.

**Comment by navis** [comment]
example forward context for HDFS in CSV format.
```
"context": {
  "forwardURL": "hdfs://localhost:9000/some/directory",
  "forwardContext": {
    "format": "csv",
    "columns": ["market", "quality", "placement", "index"],
    "nullValue": "NULL"
}
```

**Comment by CHOIJAEHONG1** [comment]
@navis I am just wondering whether we could introduce a flag that prevents the result sequence materialized in the output or other ways to do the similar things. This is beacuse the client would be expected to get the result from the given forwardURL, not from the HTTP response and it takes a long time to produce such a large number of rows, which is not used.

**Comment by navis** [comment]
@CHOIJAEHONG1 current implementation returns empty sequence when `forwardURL != null`.

**Comment by CHOIJAEHONG1** [comment]
@navis I got it. Thank you.

**Comment by HyukjinKwon** [comment]
+1

**Comment by HyukjinKwon** [comment]
Hi @navis , Do you mind if I ask a question please?

It seems arguments are only allowed as string because it uses `Map<String, String>` and we can pass a option with a numeric type value.

```json
...
"context": {
  "forwardURL": "hdfs://localhost:9000/some/directory",
  "forwardContext": {
    "format": "anotherFormat",
    "optionA": 123
  }
}
...
```

Is this intendedly done like this?

**Comment by navis** [comment]
@HyukjinKwon Because it was enough to cover all our parameters but it can be `Map<String, Object>`. I'll address that.

**Comment by navis** [comment]
Rebased on master and now it supports excel types and takes Map<String, Object> as parameter.

**Comment by navis** [comment]
Support orc format and other hadoop file systems (viewfs, ftp, har, hdfs, hftp, hsftp, webhdfs, swebhdfs, etc.)

**Pull request closed without merging**
