### PR TITLE
Enable Spotbugs NP_NONNULL_RETURN_VIOLATION

### PR DESCRIPTION
**Pull request by Fokko**
Enables Spotbugs `NP_NONNULL_RETURN_VIOLATION` rule. This checks of functions possibly return a `null` value but don't have the correct annotation.

<hr>

This PR has:
- [x] been self-reviewed.

### CODE REVIEW

**Comment by Fokko** [comment]
Rebased onto master

**Comment by Fokko** [comment]
Rebased onto master

**Comment by Fokko** [comment]
@leventov Can we move this forward?

**Comment by leventov** [comment]
@Fokko in general, please try to write to dev mailing list to draw attention of committers to the problem.

**Comment by Fokko** [comment]
@leventov I will, thanks for merging!

**Pull request merged**
