### PR TITLE
Refactoring some APIs in IndexMergerV9 and adding Builders to tuningConfigs

### PR DESCRIPTION
**Pull request by jihoonson**
Sorry for the large PR. 

I refactored two things. First, I added `Builder` classes to the tuningConfig classes to avoid weird constructor calls with all null parameters and modify them whenever we add a new configuration. Second, I changed some IndexMergerV9 APIs to use `DimensionDesc` and `MetricDesc` instead of individual collections of column names, handlers, columnCapabilities, etc.

### CODE REVIEW

**Comment by gianm** [comment]
Nice!!

The integration test error - is it real?

**Comment by b-slim** [comment]
@jihoonson can you please explain how the `numFilesPerMerge ` can prevent the OOM? and how a Simple Druid User will set the right value for this config?

**Comment by jihoonson** [comment]
@b-slim OMG, I've just realized that this does fix nothing. I think the refactoring part is still worth. I'll revert the incremental merging part and change the title. Thanks for noticing this.

**Comment by jihoonson** [comment]
I think this PR is too big for small benefit. Closing this.

**Pull request closed without merging**
