### PR TITLE
make COMPLEX column optionally filterable in Druid code

### PR DESCRIPTION
**Pull request by himanshug**
This patch provides the ability for a custom COMPLEX column writer to override the filterability of the column by setting it in `ColumnCapabilities` .

I'm writing a custom aggregator.. extension takes full control of column representation by writing custom GenericColumnSerializer, and stores bitmaps for fast filtering based on values in this column.

### CODE REVIEW

**Comment by clintropolis** [comment]
Would it make sense to add a `canFilter` method to `ColumnCapabilities` to have a finer level of control than just mapping filterability directly to `ValueType`?

**Comment by himanshug** [comment]
> Would it make sense to add a canFilter method to ColumnCapabilities to have a finer level of control than just mapping filterability directly to ValueType?

Actually I think existence of `Filterable.FILTERABLE_TYPE` is redundant. For me, ColumnCapability.hasBitmapIndexes() is already the indication whether column supports filtering or not. So, one thing to do is to remove `Filterable.FILTERABLE_TYPE` altogether and adjust the code in `ColumnSelectorBitmapIndexSelector` to not use that.

however, I would like to keep things simple for this PR and not cause any unwanted side effects as above suggestion needs to get tested appropriately.

**Comment by gianm** [comment]
> Actually I think existence of Filterable.FILTERABLE_TYPE is redundant. For me, ColumnCapability.hasBitmapIndexes() is already the indication whether column supports filtering or not.

They don't mean the same thing: for example, long columns are filterable but do not have bitmap indexes. IMO a capability makes sense and is a good way to solve this.

**Comment by himanshug** [comment]
@gianm agree that columns can be filterable without bitmap indexes. however, independently,
only use of `Filter.FILTERABLE_TYPE` is in `ColumnSelectorBitmapIndexSelector.columnSupportsFiltering(column)` which looks like

```
  private static boolean columnSupportsFiltering(Column column)
  {
    ValueType columnType = column.getCapabilities().getType();
    return Filters.FILTERABLE_TYPES.contains(columnType);
  }
``` 

and at its call sites, it is used to check whether to work with an empty bitmap or get one from column. it appears, everything would stay exactly same even if I changed above implementation to...

```
  private static boolean columnSupportsFiltering(Column column)
  {
     return column.getCapabilities().hasBitmapIndexes();
  }
```

with above done, there is no more any usage of `Filter.FILTERABLE_TYPE` .

I must be missing something.

**Comment by gianm** [comment]
@himanshug probably it makes sense for this new capability to always be true for string, long, float, double; and for it to be false by default for complex, but it can be overridden.

**Comment by clintropolis** [comment]
`@SuppressWarnings("unused")` I believe

**Comment by himanshug** [comment]
@clintropolis thanks, dint realize it was same as that for intellij... let me add that.

**Comment by clintropolis** [comment]
Hmm, I might be confusing it with intellij 😛

**Comment by clintropolis** [comment]
If it's not that it's probably 
```
 // noinspection unused
```
?

**Comment by himanshug** [comment]
no, I think you are right ... teamcity is from jetbrains and uses same set of inspections. so I guess it would be same... but the build will confirm soon.

**Pull request merged**
