### PR TITLE
Remove some unnecessary task storage internal APIs.

### PR DESCRIPTION
**Pull request by gianm**
Code cleanup, with one side effect (described below).

- Remove MetadataStorageActionHandler's getInactiveStatusesSince and getActiveEntriesWithStatus.
- Remove TaskStorage's getCreatedDateTimeAndDataSource.
- Remove TaskStorageQueryAdapter's getCreatedTime, and getCreatedDateAndDataSource.
- Migrated all callers to getActiveTaskInfo and getCompletedTaskInfo.

This has one side effect: since getActiveTaskInfo (new) warns and continues when it
sees unreadable tasks, but getActiveEntriesWithStatus (old) threw an exception when it
encountered those, it means that after this patch bad tasks will be ignored when
syncing from metadata storage rather than causing an exception to be thrown.

IMO, this is an improvement, since the most likely reason for bad tasks is either:

- A new version introduced an additional validation, and a pre-existing task doesn't
  pass it.
- You are rolling back from a newer version to an older version.

In both cases, I believe you would want to skip tasks that can't be deserialized,
rather than blocking overlord startup.

### CODE REVIEW

**Comment by gianm** [comment]
The error looks like the travis cache got corrupted? I cleared it and tried the job again.

```[INFO] Changes detected - recompiling the module!
[INFO] Compiling 191 source files to /home/travis/build/apache/incubator-druid/java-util/target/classes
error: error reading /home/travis/.m2/repository/io/netty/netty-transport/4.0.52.Final/netty-transport-4.0.52.Final.jar; error in opening zip file
An exception has occurred in the compiler (9-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.util.zip.ZipError: zip END header not found
	at com.sun.nio.zipfs.ZipFileSystem.zerror(ZipFileSystem.java:1605)
```

**Comment by jihoonson** [comment]
Please check this:

```
[ERROR] /home/travis/build/apache/incubator-druid/common/src/main/java/io/druid/metadata/MetadataStorageActionHandler.java:24:8: Unused import - io.druid.java.util.common.Pair. [UnusedImports]
Audit done.
```

**Comment by gianm** [comment]
I removed that and re-pushed.

**Comment by asdf2014** [comment]
Hi, @gianm . There are still unused `import` clauses. IMO, we should add the `--fail-at-end` option into the maven command for the `strictly compiled' part, and then we can get all these error messages at once, including checkstyle, compile, testcases, etc.

**Comment by asdf2014** [comment]
@gianm If you think this is necessary, I will create a PR for it. :smile:

**Comment by gianm** [comment]
@asdf2014 I will fix them and re-push.

Anything that makes the CI failure message more useful sounds great 😄

**Pull request merged**
