### PR TITLE
Fix ClassCastException for TopN with long-type dimension

### LINKED ISSUE #8348: Integer->Long ClassCastException in TopN query
`TopNNumericResultBuilder` can hit a ClassCastException on the broker when a query uses a long dimension, due to Jackson behavior where a number gets deserialized as an integer instead of as a long if it fits in 32 bits.

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
	at java.lang.Long.compareTo(Long.java:54) ~[?:1.8.0_202]
	at org.apache.druid.query.topn.TopNNumericResultBuilder$1.compare(TopNNumericResultBuilder.java:67) ~[druid-processing-0.16.0-incubating-SNAPSHOT.jar:0.16.0-incubating-SNAPSHOT]
	at org.apache.druid.query.topn.TopNNumericResultBuilder$1.compare(TopNNumericResultBuilder.java:52) ~[druid-processing-0.16.0-incubating-SNAPSHOT.jar:0.16.0-incubating-SNAPSHOT]
	at org.apache.druid.query.topn.TopNNumericResultBuilder.lambda$new$0(TopNNumericResultBuilder.java:99) ~[druid-processing-0.16.0-incubating-SNAPSHOT.jar:0.16.0-incubating-SNAPSHOT]
	at java.util.PriorityQueue.siftUpUsingComparator(PriorityQueue.java:670) ~[?:1.8.0_202]
	at java.util.PriorityQueue.siftUp(PriorityQueue.java:646) ~[?:1.8.0_202]
	at java.util.PriorityQueue.offer(PriorityQueue.java:345) ~[?:1.8.0_202]
	at java.util.PriorityQueue.add(PriorityQueue.java:322) ~[?:1.8.0_202]
	at org.apache.druid.query.topn.TopNNumericResultBuilder.addEntry(TopNNumericResultBuilder.java:204) ~[druid-processing-0.16.0-incubating-SNAPSHOT.jar:0.16.0-incubating-SNAPSHOT]
	at org.apache.druid.query.topn.TopNBinaryFn.apply(TopNBinaryFn.java:132) ~[druid-processing-0.16.0-incubating-SNAPSHOT.jar:0.16.0-incubating-SNAPSHOT]
	at org.apache.druid.query.topn.TopNBinaryFn.apply(TopNBinaryFn.java:39) ~[druid-processing-0.16.0-incubating-SNAPSHOT.jar:0.16.0-incubating-SNAPSHOT]
	at org.apache.druid.common.guava.CombiningSequence$CombiningYieldingAccumulator.accumulate(CombiningSequence.java:210) ~[druid-core-0.16.0-incubating-SNAPSHOT.jar:0.16.0-incubating-SNAPSHOT]
	at org.apache.druid.java.util.common.guava.MergeSequence.makeYielder(MergeSequence.java:104) ~[druid-core-0.16.0-incubating-SNAPSHOT.jar:0.16.0-incubating-SNAPSHOT]
```

The following data and specs can be used to reproduce the issue.

Data
```
{"time": "2015-09-12T00:46:58.771Z", "id": 10, "val": 5}
{"time": "2015-09-13T00:46:58.771Z", "id": 8147483647, "val": 5}
```

Ingest spec
```
{
  "type" : "index",
  "spec" : {
    "dataSchema" : {
      "dataSource" : "topnmerge",
      "parser" : {
        "type" : "string",
        "parseSpec" : {
          "format" : "json",
          "dimensionsSpec" : {
            "dimensions" : [
              {
                "type":"long",
                "name":"id"
              }
            ],
            "dimensionExclusions" : []
          },
          "timestampSpec" : {
            "format" : "auto",
            "column" : "time"
          }
        }
      },
      "metricsSpec" : [
        { "type" : "count", "name" : "count", "type" : "count" },
        { "type" : "longSum", "name" : "val", "fieldName" : "val" }
      ],
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "day",
        "queryGranularity" : "none",
        "intervals" : ["2015-09-01/2015-09-20"],
        "rollup" : false
      }
    },
    "ioConfig" : {
      "type" : "index",
      "firehose" : {
        "type" : "local",
        "baseDir" : "quickstart/topnmerge/",
        "filter" : "data.json"
      },
      "appendToExisting" : false
    },
    "tuningConfig" : {
      "type" : "index",
      "targetPartitionSize" : null,
      "maxRowsInMemory" : 1000,
      "forceGuaranteedRollup" : true,
      "numShards": 1
    }
  }
}
```

Query
```
{
  "queryType": "topN",
  "dataSource": {
    "type": "table",
    "name": "topnmerge"
  },
  "virtualColumns": [],
  "dimension": {
    "type": "default",
    "dimension": "id",
    "outputName": "d0",
    "outputType": "LONG"
  },
  "metric": {
    "type": "numeric",
    "metric": "a0"
  },
  "threshold": 1000,
  "intervals": {
    "type": "intervals",
    "intervals": [
      "-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"
    ]
  },
  "filter": null,
  "granularity": {
    "type": "all"
  },
  "aggregations": [
    {
      "type": "longSum",
      "name": "a0",
      "fieldName": "val",
      "expression": null
    }
  ],
  "postAggregations": [],
  "context": {
  },
  "descending": false
}
```

With the examples above, the issue can be reproduced on a quickstart cluster with 2 historicals, by putting each historical in a separate tier and setting load rules such that each tier loads only one day of data (9/12 or 9/13).

### PR DESCRIPTION
**Pull request by jon-wei**
This PR fixes #8348 by ensuring that `DimValHolder` converts dimension values to the output type specified in the dimension spec of the TopN query.

This PR has:
- [x] been self-reviewed.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by gianm** [comment]
> LGTM but a test of some sort would be appreciated.

(Beyond the test in a live cluster, I mean.)

**Comment by jon-wei** [comment]
I had looked into how to make a test for this, for unit testing, I initially tried setting up a `toolChest.mergeResults` merging test (like how TopNBenchmark merges queryable indices) using the replication case described in https://github.com/apache/incubator-druid/issues/8348, but that doesn't have the JSON serde step.

An integration test could be made to specifically test this, but the test would require two historicals, and the integration tests are already somewhat resource constrained (it also feels a little overkill to me)

I could make a unit test that just tests DimValHolder type conversion, but that doesn't really test the original bug situation.

Any thoughts?

**Comment by gianm** [comment]
Hmm, that's a good point. I think given those facts, a test of DimValHolder would be sufficient for this patch, even though it doesn't test the original bug situation. Perhaps in the future we could consider testing this class of bugs through a more powerful integration testing framework.

**Comment by jon-wei** [comment]
Only coveralls check failed, and coveralls is being removed, will go ahead and merge

**Pull request merged**
